apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zenx

resources:
  - namespace.yaml
  - configmap.yaml
  - services/auth-service.yaml
  - services/workout-service.yaml
  - services/exercise-service.yaml
  - services/profile-service.yaml
  - services/analytics-service.yaml
  - services/notification-service.yaml
  - services/gateway.yaml


