// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exercise/v1/exercise.proto

package exercisev1

import (
	v1 "github.com/zenx/backend/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exercise struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category              string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	PrimaryMuscleGroup    string                 `protobuf:"bytes,5,opt,name=primary_muscle_group,json=primaryMuscleGroup,proto3" json:"primary_muscle_group,omitempty"`
	SecondaryMuscleGroups []string               `protobuf:"bytes,6,rep,name=secondary_muscle_groups,json=secondaryMuscleGroups,proto3" json:"secondary_muscle_groups,omitempty"`
	EquipmentRequired     string                 `protobuf:"bytes,7,opt,name=equipment_required,json=equipmentRequired,proto3" json:"equipment_required,omitempty"`
	DifficultyLevel       string                 `protobuf:"bytes,8,opt,name=difficulty_level,json=difficultyLevel,proto3" json:"difficulty_level,omitempty"`
	IsCustom              bool                   `protobuf:"varint,9,opt,name=is_custom,json=isCustom,proto3" json:"is_custom,omitempty"`
	CreatedBy             string                 `protobuf:"bytes,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_exercise_v1_exercise_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_v1_exercise_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_exercise_v1_exercise_proto_rawDescGZIP(), []int{0}
}

func (x *Exercise) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Exercise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exercise) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Exercise) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Exercise) GetPrimaryMuscleGroup() string {
	if x != nil {
		return x.PrimaryMuscleGroup
	}
	return ""
}

func (x *Exercise) GetSecondaryMuscleGroups() []string {
	if x != nil {
		return x.SecondaryMuscleGroups
	}
	return nil
}

func (x *Exercise) GetEquipmentRequired() string {
	if x != nil {
		return x.EquipmentRequired
	}
	return ""
}

func (x *Exercise) GetDifficultyLevel() string {
	if x != nil {
		return x.DifficultyLevel
	}
	return ""
}

func (x *Exercise) GetIsCustom() bool {
	if x != nil {
		return x.IsCustom
	}
	return false
}

func (x *Exercise) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercise      *Exercise              `protobuf:"bytes,1,opt,name=exercise,proto3" json:"exercise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExerciseRequest) Reset() {
	*x = CreateExerciseRequest{}
	mi := &file_exercise_v1_exercise_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExerciseRequest) ProtoMessage() {}

func (x *CreateExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_v1_exercise_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExerciseRequest.ProtoReflect.Descriptor instead.
func (*CreateExerciseRequest) Descriptor() ([]byte, []int) {
	return file_exercise_v1_exercise_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExerciseRequest) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

type UpdateExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	Exercise      *Exercise              `protobuf:"bytes,2,opt,name=exercise,proto3" json:"exercise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExerciseRequest) Reset() {
	*x = UpdateExerciseRequest{}
	mi := &file_exercise_v1_exercise_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExerciseRequest) ProtoMessage() {}

func (x *UpdateExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_v1_exercise_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExerciseRequest.ProtoReflect.Descriptor instead.
func (*UpdateExerciseRequest) Descriptor() ([]byte, []int) {
	return file_exercise_v1_exercise_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateExerciseRequest) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *UpdateExerciseRequest) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

type DeleteExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExerciseRequest) Reset() {
	*x = DeleteExerciseRequest{}
	mi := &file_exercise_v1_exercise_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExerciseRequest) ProtoMessage() {}

func (x *DeleteExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_v1_exercise_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExerciseRequest.ProtoReflect.Descriptor instead.
func (*DeleteExerciseRequest) Descriptor() ([]byte, []int) {
	return file_exercise_v1_exercise_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteExerciseRequest) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

type GetExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseRequest) Reset() {
	*x = GetExerciseRequest{}
	mi := &file_exercise_v1_exercise_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseRequest) ProtoMessage() {}

func (x *GetExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_v1_exercise_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseRequest.ProtoReflect.Descriptor instead.
func (*GetExerciseRequest) Descriptor() ([]byte, []int) {
	return file_exercise_v1_exercise_proto_rawDescGZIP(), []int{4}
}

func (x *GetExerciseRequest) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

type ListExercisesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Categories    []string               `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExercisesRequest) Reset() {
	*x = ListExercisesRequest{}
	mi := &file_exercise_v1_exercise_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExercisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExercisesRequest) ProtoMessage() {}

func (x *ListExercisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_v1_exercise_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExercisesRequest.ProtoReflect.Descriptor instead.
func (*ListExercisesRequest) Descriptor() ([]byte, []int) {
	return file_exercise_v1_exercise_proto_rawDescGZIP(), []int{5}
}

func (x *ListExercisesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListExercisesRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListExercisesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercises     []*Exercise            `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExercisesResponse) Reset() {
	*x = ListExercisesResponse{}
	mi := &file_exercise_v1_exercise_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExercisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExercisesResponse) ProtoMessage() {}

func (x *ListExercisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_v1_exercise_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExercisesResponse.ProtoReflect.Descriptor instead.
func (*ListExercisesResponse) Descriptor() ([]byte, []int) {
	return file_exercise_v1_exercise_proto_rawDescGZIP(), []int{6}
}

func (x *ListExercisesResponse) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

var File_exercise_v1_exercise_proto protoreflect.FileDescriptor

const file_exercise_v1_exercise_proto_rawDesc = "" +
	"\n" +
	"\x1aexercise/v1/exercise.proto\x12\x10zenx.exercise.v1\x1a\x16common/v1/common.proto\"\xec\x02\n" +
	"\bExercise\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x120\n" +
	"\x14primary_muscle_group\x18\x05 \x01(\tR\x12primaryMuscleGroup\x126\n" +
	"\x17secondary_muscle_groups\x18\x06 \x03(\tR\x15secondaryMuscleGroups\x12-\n" +
	"\x12equipment_required\x18\a \x01(\tR\x11equipmentRequired\x12)\n" +
	"\x10difficulty_level\x18\b \x01(\tR\x0fdifficultyLevel\x12\x1b\n" +
	"\tis_custom\x18\t \x01(\bR\bisCustom\x12\x1d\n" +
	"\n" +
	"created_by\x18\n" +
	" \x01(\tR\tcreatedBy\"O\n" +
	"\x15CreateExerciseRequest\x126\n" +
	"\bexercise\x18\x01 \x01(\v2\x1a.zenx.exercise.v1.ExerciseR\bexercise\"p\n" +
	"\x15UpdateExerciseRequest\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\x126\n" +
	"\bexercise\x18\x02 \x01(\v2\x1a.zenx.exercise.v1.ExerciseR\bexercise\"8\n" +
	"\x15DeleteExerciseRequest\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\"5\n" +
	"\x12GetExerciseRequest\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\"L\n" +
	"\x14ListExercisesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1e\n" +
	"\n" +
	"categories\x18\x02 \x03(\tR\n" +
	"categories\"Q\n" +
	"\x15ListExercisesResponse\x128\n" +
	"\texercises\x18\x01 \x03(\v2\x1a.zenx.exercise.v1.ExerciseR\texercises2\xc4\x03\n" +
	"\x0fExerciseService\x12U\n" +
	"\x0eCreateExercise\x12'.zenx.exercise.v1.CreateExerciseRequest\x1a\x1a.zenx.exercise.v1.Exercise\x12U\n" +
	"\x0eUpdateExercise\x12'.zenx.exercise.v1.UpdateExerciseRequest\x1a\x1a.zenx.exercise.v1.Exercise\x12P\n" +
	"\x0eDeleteExercise\x12'.zenx.exercise.v1.DeleteExerciseRequest\x1a\x15.zenx.common.v1.Empty\x12O\n" +
	"\vGetExercise\x12$.zenx.exercise.v1.GetExerciseRequest\x1a\x1a.zenx.exercise.v1.Exercise\x12`\n" +
	"\rListExercises\x12&.zenx.exercise.v1.ListExercisesRequest\x1a'.zenx.exercise.v1.ListExercisesResponseB6Z4github.com/zenx/backend/proto/exercise/v1;exercisev1b\x06proto3"

var (
	file_exercise_v1_exercise_proto_rawDescOnce sync.Once
	file_exercise_v1_exercise_proto_rawDescData []byte
)

func file_exercise_v1_exercise_proto_rawDescGZIP() []byte {
	file_exercise_v1_exercise_proto_rawDescOnce.Do(func() {
		file_exercise_v1_exercise_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exercise_v1_exercise_proto_rawDesc), len(file_exercise_v1_exercise_proto_rawDesc)))
	})
	return file_exercise_v1_exercise_proto_rawDescData
}

var file_exercise_v1_exercise_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_exercise_v1_exercise_proto_goTypes = []any{
	(*Exercise)(nil),              // 0: zenx.exercise.v1.Exercise
	(*CreateExerciseRequest)(nil), // 1: zenx.exercise.v1.CreateExerciseRequest
	(*UpdateExerciseRequest)(nil), // 2: zenx.exercise.v1.UpdateExerciseRequest
	(*DeleteExerciseRequest)(nil), // 3: zenx.exercise.v1.DeleteExerciseRequest
	(*GetExerciseRequest)(nil),    // 4: zenx.exercise.v1.GetExerciseRequest
	(*ListExercisesRequest)(nil),  // 5: zenx.exercise.v1.ListExercisesRequest
	(*ListExercisesResponse)(nil), // 6: zenx.exercise.v1.ListExercisesResponse
	(*v1.Empty)(nil),              // 7: zenx.common.v1.Empty
}
var file_exercise_v1_exercise_proto_depIdxs = []int32{
	0, // 0: zenx.exercise.v1.CreateExerciseRequest.exercise:type_name -> zenx.exercise.v1.Exercise
	0, // 1: zenx.exercise.v1.UpdateExerciseRequest.exercise:type_name -> zenx.exercise.v1.Exercise
	0, // 2: zenx.exercise.v1.ListExercisesResponse.exercises:type_name -> zenx.exercise.v1.Exercise
	1, // 3: zenx.exercise.v1.ExerciseService.CreateExercise:input_type -> zenx.exercise.v1.CreateExerciseRequest
	2, // 4: zenx.exercise.v1.ExerciseService.UpdateExercise:input_type -> zenx.exercise.v1.UpdateExerciseRequest
	3, // 5: zenx.exercise.v1.ExerciseService.DeleteExercise:input_type -> zenx.exercise.v1.DeleteExerciseRequest
	4, // 6: zenx.exercise.v1.ExerciseService.GetExercise:input_type -> zenx.exercise.v1.GetExerciseRequest
	5, // 7: zenx.exercise.v1.ExerciseService.ListExercises:input_type -> zenx.exercise.v1.ListExercisesRequest
	0, // 8: zenx.exercise.v1.ExerciseService.CreateExercise:output_type -> zenx.exercise.v1.Exercise
	0, // 9: zenx.exercise.v1.ExerciseService.UpdateExercise:output_type -> zenx.exercise.v1.Exercise
	7, // 10: zenx.exercise.v1.ExerciseService.DeleteExercise:output_type -> zenx.common.v1.Empty
	0, // 11: zenx.exercise.v1.ExerciseService.GetExercise:output_type -> zenx.exercise.v1.Exercise
	6, // 12: zenx.exercise.v1.ExerciseService.ListExercises:output_type -> zenx.exercise.v1.ListExercisesResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_exercise_v1_exercise_proto_init() }
func file_exercise_v1_exercise_proto_init() {
	if File_exercise_v1_exercise_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exercise_v1_exercise_proto_rawDesc), len(file_exercise_v1_exercise_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exercise_v1_exercise_proto_goTypes,
		DependencyIndexes: file_exercise_v1_exercise_proto_depIdxs,
		MessageInfos:      file_exercise_v1_exercise_proto_msgTypes,
	}.Build()
	File_exercise_v1_exercise_proto = out.File
	file_exercise_v1_exercise_proto_goTypes = nil
	file_exercise_v1_exercise_proto_depIdxs = nil
}
