// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    string `json:"expiresAt"`
}

type DateRangeInput struct {
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
}

type Exercise struct {
	ID                    string   `json:"id"`
	Name                  string   `json:"name"`
	Description           *string  `json:"description,omitempty"`
	Category              *string  `json:"category,omitempty"`
	PrimaryMuscleGroup    *string  `json:"primaryMuscleGroup,omitempty"`
	SecondaryMuscleGroups []string `json:"secondaryMuscleGroups"`
	EquipmentRequired     *string  `json:"equipmentRequired,omitempty"`
	DifficultyLevel       *string  `json:"difficultyLevel,omitempty"`
	IsCustom              bool     `json:"isCustom"`
	CreatedAt             *string  `json:"createdAt,omitempty"`
}

type ExerciseInput struct {
	Name                  string   `json:"name"`
	Description           *string  `json:"description,omitempty"`
	Category              *string  `json:"category,omitempty"`
	PrimaryMuscleGroup    *string  `json:"primaryMuscleGroup,omitempty"`
	SecondaryMuscleGroups []string `json:"secondaryMuscleGroups,omitempty"`
	EquipmentRequired     *string  `json:"equipmentRequired,omitempty"`
	DifficultyLevel       *string  `json:"difficultyLevel,omitempty"`
	IsCustom              *bool    `json:"isCustom,omitempty"`
}

type ExercisePerformance struct {
	ExerciseID        string                  `json:"exerciseId"`
	ExerciseName      string                  `json:"exerciseName"`
	HeaviestWeight    *float64                `json:"heaviestWeight,omitempty"`
	ProjectedOneRm    *float64                `json:"projectedOneRM,omitempty"`
	BestSetVolume     *float64                `json:"bestSetVolume,omitempty"`
	BestSessionVolume *float64                `json:"bestSessionVolume,omitempty"`
	MostReps          *int                    `json:"mostReps,omitempty"`
	PersonalRecords   []*PersonalRecord       `json:"personalRecords"`
	History           []*WorkoutExerciseEntry `json:"history"`
}

type ExerciseRecord struct {
	ExerciseID    string   `json:"exerciseId"`
	ExerciseName  string   `json:"exerciseName"`
	WorkoutCount  int      `json:"workoutCount"`
	LastPerformed *string  `json:"lastPerformed,omitempty"`
	AverageWeight *float64 `json:"averageWeight,omitempty"`
}

type FeedCommentConnection struct {
	Comments   []*PostComment `json:"comments"`
	NextCursor *string        `json:"nextCursor,omitempty"`
}

type FeedConnection struct {
	Edges      []*FeedPost `json:"edges"`
	NextCursor *string     `json:"nextCursor,omitempty"`
}

type FeedPost struct {
	ID             string   `json:"id"`
	WorkoutID      string   `json:"workoutId"`
	UserID         string   `json:"userId"`
	Caption        *string  `json:"caption,omitempty"`
	ImageURL       *string  `json:"imageUrl,omitempty"`
	CreatedAt      string   `json:"createdAt"`
	UpdatedAt      string   `json:"updatedAt"`
	LikesCount     int      `json:"likesCount"`
	CommentsCount  int      `json:"commentsCount"`
	IsLiked        bool     `json:"isLiked"`
	LikedByUserIds []string `json:"likedByUserIds,omitempty"`
	Workout        *Workout `json:"workout"`
	AuthorProfile  *Profile `json:"authorProfile,omitempty"`
}

type Measurement struct {
	ID                string   `json:"id"`
	UserID            string   `json:"userId"`
	MeasurementDate   string   `json:"measurementDate"`
	WeightKg          *float64 `json:"weightKg,omitempty"`
	BodyFatPercentage *float64 `json:"bodyFatPercentage,omitempty"`
	MuscleMassKg      *float64 `json:"muscleMassKg,omitempty"`
	MeasurementsJSON  *string  `json:"measurementsJson,omitempty"`
	CreatedAt         string   `json:"createdAt"`
}

type MeasurementInput struct {
	MeasurementDate   string   `json:"measurementDate"`
	WeightKg          *float64 `json:"weightKg,omitempty"`
	BodyFatPercentage *float64 `json:"bodyFatPercentage,omitempty"`
	MuscleMassKg      *float64 `json:"muscleMassKg,omitempty"`
	MeasurementsJSON  *string  `json:"measurementsJson,omitempty"`
}

type MeasurementRangeInput struct {
	Start *string `json:"start,omitempty"`
	End   *string `json:"end,omitempty"`
}

type MuscleGroupStat struct {
	MuscleGroup string  `json:"muscleGroup"`
	SetCount    int     `json:"setCount"`
	Volume      float64 `json:"volume"`
	Percentage  float64 `json:"percentage"`
}

type Mutation struct {
}

type Notification struct {
	ID           string               `json:"id"`
	UserID       string               `json:"userId"`
	Type         string               `json:"type"`
	Template     *string              `json:"template,omitempty"`
	Status       *string              `json:"status,omitempty"`
	Title        string               `json:"title"`
	Body         string               `json:"body"`
	Data         []*NotificationDatum `json:"data,omitempty"`
	IsRead       bool                 `json:"isRead"`
	ScheduledFor *string              `json:"scheduledFor,omitempty"`
	SentAt       *string              `json:"sentAt,omitempty"`
	CreatedAt    string               `json:"createdAt"`
}

type NotificationConnection struct {
	Nodes       []*Notification `json:"nodes"`
	NextCursor  *string         `json:"nextCursor,omitempty"`
	UnreadCount int             `json:"unreadCount"`
}

type NotificationDatum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type PersonalRecord struct {
	ExerciseID string    `json:"exerciseId"`
	RecordType string    `json:"recordType"`
	Value      float64   `json:"value"`
	AchievedAt string    `json:"achievedAt"`
	Exercise   *Exercise `json:"exercise,omitempty"`
}

type PostComment struct {
	ID            string   `json:"id"`
	PostID        string   `json:"postId"`
	UserID        string   `json:"userId"`
	Body          string   `json:"body"`
	CreatedAt     string   `json:"createdAt"`
	AuthorProfile *Profile `json:"authorProfile,omitempty"`
}

type Profile struct {
	ID          string  `json:"id"`
	DisplayName *string `json:"displayName,omitempty"`
	Bio         *string `json:"bio,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	DateOfBirth *string `json:"dateOfBirth,omitempty"`
	Gender      *string `json:"gender,omitempty"`
}

type ProfileInput struct {
	DisplayName *string `json:"displayName,omitempty"`
	Bio         *string `json:"bio,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	DateOfBirth *string `json:"dateOfBirth,omitempty"`
	Gender      *string `json:"gender,omitempty"`
}

type ProgressSnapshot struct {
	UserID        string            `json:"userId"`
	CapturedAt    string            `json:"capturedAt"`
	TotalVolumeKg *float64          `json:"totalVolumeKg,omitempty"`
	AverageRpe    *float64          `json:"averageRpe,omitempty"`
	WorkoutCount  int               `json:"workoutCount"`
	Prs           []*PersonalRecord `json:"prs"`
}

type Query struct {
}

type UpdateExerciseInput struct {
	Name                  *string  `json:"name,omitempty"`
	Description           *string  `json:"description,omitempty"`
	Category              *string  `json:"category,omitempty"`
	PrimaryMuscleGroup    *string  `json:"primaryMuscleGroup,omitempty"`
	SecondaryMuscleGroups []string `json:"secondaryMuscleGroups,omitempty"`
	EquipmentRequired     *string  `json:"equipmentRequired,omitempty"`
	DifficultyLevel       *string  `json:"difficultyLevel,omitempty"`
	IsCustom              *bool    `json:"isCustom,omitempty"`
}

type UpdateWorkoutInput struct {
	Name        *string                 `json:"name,omitempty"`
	Notes       *string                 `json:"notes,omitempty"`
	Exercises   []*WorkoutExerciseInput `json:"exercises,omitempty"`
	StartedAt   *string                 `json:"startedAt,omitempty"`
	CompletedAt *string                 `json:"completedAt,omitempty"`
}

type User struct {
	ID          string   `json:"id"`
	Email       string   `json:"email"`
	DisplayName *string  `json:"displayName,omitempty"`
	Profile     *Profile `json:"profile,omitempty"`
}

type Workout struct {
	ID          string             `json:"id"`
	UserID      string             `json:"userId"`
	Name        string             `json:"name"`
	Notes       *string            `json:"notes,omitempty"`
	StartedAt   *string            `json:"startedAt,omitempty"`
	CompletedAt *string            `json:"completedAt,omitempty"`
	Exercises   []*WorkoutExercise `json:"exercises"`
}

type WorkoutCalendar struct {
	StartDate     string   `json:"startDate"`
	EndDate       string   `json:"endDate"`
	WorkoutDays   []string `json:"workoutDays"`
	TotalWorkouts int      `json:"totalWorkouts"`
}

type WorkoutExercise struct {
	ExerciseID string        `json:"exerciseId"`
	Order      int           `json:"order"`
	Sets       []*WorkoutSet `json:"sets"`
}

type WorkoutExerciseEntry struct {
	WorkoutID string   `json:"workoutId"`
	Date      string   `json:"date"`
	Weight    float64  `json:"weight"`
	Reps      int      `json:"reps"`
	OneRm     *float64 `json:"oneRM,omitempty"`
	Volume    *float64 `json:"volume,omitempty"`
}

type WorkoutExerciseInput struct {
	ExerciseID string             `json:"exerciseId"`
	Order      int                `json:"order"`
	Sets       []*WorkoutSetInput `json:"sets"`
}

type WorkoutInput struct {
	UserID    string                  `json:"userId"`
	Name      string                  `json:"name"`
	Notes     *string                 `json:"notes,omitempty"`
	Exercises []*WorkoutExerciseInput `json:"exercises,omitempty"`
}

type WorkoutSet struct {
	SetNumber int      `json:"setNumber"`
	Reps      *int     `json:"reps,omitempty"`
	WeightKg  *float64 `json:"weightKg,omitempty"`
	Rpe       *float64 `json:"rpe,omitempty"`
	Completed *bool    `json:"completed,omitempty"`
}

type WorkoutSetInput struct {
	SetNumber int      `json:"setNumber"`
	Reps      *int     `json:"reps,omitempty"`
	WeightKg  *float64 `json:"weightKg,omitempty"`
	Rpe       *float64 `json:"rpe,omitempty"`
	Notes     *string  `json:"notes,omitempty"`
	Completed *bool    `json:"completed,omitempty"`
}
