// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetProgressSnapshot_FullMethodName = "/zenx.analytics.v1.AnalyticsService/GetProgressSnapshot"
	AnalyticsService_ListPersonalRecords_FullMethodName = "/zenx.analytics.v1.AnalyticsService/ListPersonalRecords"
	AnalyticsService_RecalculateMetrics_FullMethodName  = "/zenx.analytics.v1.AnalyticsService/RecalculateMetrics"
	AnalyticsService_GetWorkoutCalendar_FullMethodName  = "/zenx.analytics.v1.AnalyticsService/GetWorkoutCalendar"
	AnalyticsService_GetMuscleGroupStats_FullMethodName = "/zenx.analytics.v1.AnalyticsService/GetMuscleGroupStats"
	AnalyticsService_GetTopExercises_FullMethodName     = "/zenx.analytics.v1.AnalyticsService/GetTopExercises"
	AnalyticsService_GetExerciseStats_FullMethodName    = "/zenx.analytics.v1.AnalyticsService/GetExerciseStats"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetProgressSnapshot(ctx context.Context, in *GetProgressSnapshotRequest, opts ...grpc.CallOption) (*ProgressSnapshot, error)
	ListPersonalRecords(ctx context.Context, in *ListPersonalRecordsRequest, opts ...grpc.CallOption) (*ListPersonalRecordsResponse, error)
	RecalculateMetrics(ctx context.Context, in *RecalculateMetricsRequest, opts ...grpc.CallOption) (*RecalculateMetricsResponse, error)
	// New analytics methods
	GetWorkoutCalendar(ctx context.Context, in *GetWorkoutCalendarRequest, opts ...grpc.CallOption) (*GetWorkoutCalendarResponse, error)
	GetMuscleGroupStats(ctx context.Context, in *GetMuscleGroupStatsRequest, opts ...grpc.CallOption) (*GetMuscleGroupStatsResponse, error)
	GetTopExercises(ctx context.Context, in *GetTopExercisesRequest, opts ...grpc.CallOption) (*GetTopExercisesResponse, error)
	GetExerciseStats(ctx context.Context, in *GetExerciseStatsRequest, opts ...grpc.CallOption) (*GetExerciseStatsResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetProgressSnapshot(ctx context.Context, in *GetProgressSnapshotRequest, opts ...grpc.CallOption) (*ProgressSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressSnapshot)
	err := c.cc.Invoke(ctx, AnalyticsService_GetProgressSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) ListPersonalRecords(ctx context.Context, in *ListPersonalRecordsRequest, opts ...grpc.CallOption) (*ListPersonalRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPersonalRecordsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_ListPersonalRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) RecalculateMetrics(ctx context.Context, in *RecalculateMetricsRequest, opts ...grpc.CallOption) (*RecalculateMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecalculateMetricsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_RecalculateMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetWorkoutCalendar(ctx context.Context, in *GetWorkoutCalendarRequest, opts ...grpc.CallOption) (*GetWorkoutCalendarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkoutCalendarResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetWorkoutCalendar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetMuscleGroupStats(ctx context.Context, in *GetMuscleGroupStatsRequest, opts ...grpc.CallOption) (*GetMuscleGroupStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMuscleGroupStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetMuscleGroupStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTopExercises(ctx context.Context, in *GetTopExercisesRequest, opts ...grpc.CallOption) (*GetTopExercisesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopExercisesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTopExercises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetExerciseStats(ctx context.Context, in *GetExerciseStatsRequest, opts ...grpc.CallOption) (*GetExerciseStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExerciseStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetExerciseStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetProgressSnapshot(context.Context, *GetProgressSnapshotRequest) (*ProgressSnapshot, error)
	ListPersonalRecords(context.Context, *ListPersonalRecordsRequest) (*ListPersonalRecordsResponse, error)
	RecalculateMetrics(context.Context, *RecalculateMetricsRequest) (*RecalculateMetricsResponse, error)
	// New analytics methods
	GetWorkoutCalendar(context.Context, *GetWorkoutCalendarRequest) (*GetWorkoutCalendarResponse, error)
	GetMuscleGroupStats(context.Context, *GetMuscleGroupStatsRequest) (*GetMuscleGroupStatsResponse, error)
	GetTopExercises(context.Context, *GetTopExercisesRequest) (*GetTopExercisesResponse, error)
	GetExerciseStats(context.Context, *GetExerciseStatsRequest) (*GetExerciseStatsResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetProgressSnapshot(context.Context, *GetProgressSnapshotRequest) (*ProgressSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgressSnapshot not implemented")
}
func (UnimplementedAnalyticsServiceServer) ListPersonalRecords(context.Context, *ListPersonalRecordsRequest) (*ListPersonalRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPersonalRecords not implemented")
}
func (UnimplementedAnalyticsServiceServer) RecalculateMetrics(context.Context, *RecalculateMetricsRequest) (*RecalculateMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecalculateMetrics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetWorkoutCalendar(context.Context, *GetWorkoutCalendarRequest) (*GetWorkoutCalendarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkoutCalendar not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetMuscleGroupStats(context.Context, *GetMuscleGroupStatsRequest) (*GetMuscleGroupStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMuscleGroupStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTopExercises(context.Context, *GetTopExercisesRequest) (*GetTopExercisesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopExercises not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetExerciseStats(context.Context, *GetExerciseStatsRequest) (*GetExerciseStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExerciseStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetProgressSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetProgressSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetProgressSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetProgressSnapshot(ctx, req.(*GetProgressSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_ListPersonalRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPersonalRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).ListPersonalRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_ListPersonalRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).ListPersonalRecords(ctx, req.(*ListPersonalRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_RecalculateMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecalculateMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).RecalculateMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_RecalculateMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).RecalculateMetrics(ctx, req.(*RecalculateMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetWorkoutCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkoutCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetWorkoutCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetWorkoutCalendar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetWorkoutCalendar(ctx, req.(*GetWorkoutCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetMuscleGroupStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMuscleGroupStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetMuscleGroupStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetMuscleGroupStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetMuscleGroupStats(ctx, req.(*GetMuscleGroupStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTopExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTopExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTopExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTopExercises(ctx, req.(*GetTopExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetExerciseStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExerciseStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetExerciseStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetExerciseStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetExerciseStats(ctx, req.(*GetExerciseStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenx.analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProgressSnapshot",
			Handler:    _AnalyticsService_GetProgressSnapshot_Handler,
		},
		{
			MethodName: "ListPersonalRecords",
			Handler:    _AnalyticsService_ListPersonalRecords_Handler,
		},
		{
			MethodName: "RecalculateMetrics",
			Handler:    _AnalyticsService_RecalculateMetrics_Handler,
		},
		{
			MethodName: "GetWorkoutCalendar",
			Handler:    _AnalyticsService_GetWorkoutCalendar_Handler,
		},
		{
			MethodName: "GetMuscleGroupStats",
			Handler:    _AnalyticsService_GetMuscleGroupStats_Handler,
		},
		{
			MethodName: "GetTopExercises",
			Handler:    _AnalyticsService_GetTopExercises_Handler,
		},
		{
			MethodName: "GetExerciseStats",
			Handler:    _AnalyticsService_GetExerciseStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/v1/analytics.proto",
}
