// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *DateRange) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *DateRange) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetWorkoutCalendarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DateRange     *DateRange             `protobuf:"bytes,2,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkoutCalendarRequest) Reset() {
	*x = GetWorkoutCalendarRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkoutCalendarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkoutCalendarRequest) ProtoMessage() {}

func (x *GetWorkoutCalendarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkoutCalendarRequest.ProtoReflect.Descriptor instead.
func (*GetWorkoutCalendarRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorkoutCalendarRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWorkoutCalendarRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

type GetWorkoutCalendarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutDays   []string               `protobuf:"bytes,1,rep,name=workout_days,json=workoutDays,proto3" json:"workout_days,omitempty"`
	TotalWorkouts int32                  `protobuf:"varint,2,opt,name=total_workouts,json=totalWorkouts,proto3" json:"total_workouts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkoutCalendarResponse) Reset() {
	*x = GetWorkoutCalendarResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkoutCalendarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkoutCalendarResponse) ProtoMessage() {}

func (x *GetWorkoutCalendarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkoutCalendarResponse.ProtoReflect.Descriptor instead.
func (*GetWorkoutCalendarResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkoutCalendarResponse) GetWorkoutDays() []string {
	if x != nil {
		return x.WorkoutDays
	}
	return nil
}

func (x *GetWorkoutCalendarResponse) GetTotalWorkouts() int32 {
	if x != nil {
		return x.TotalWorkouts
	}
	return 0
}

type GetMuscleGroupStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DateRange     *DateRange             `protobuf:"bytes,2,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMuscleGroupStatsRequest) Reset() {
	*x = GetMuscleGroupStatsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMuscleGroupStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMuscleGroupStatsRequest) ProtoMessage() {}

func (x *GetMuscleGroupStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMuscleGroupStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMuscleGroupStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetMuscleGroupStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMuscleGroupStatsRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

type MuscleGroupStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MuscleGroup   string                 `protobuf:"bytes,1,opt,name=muscle_group,json=muscleGroup,proto3" json:"muscle_group,omitempty"`
	SetCount      int32                  `protobuf:"varint,2,opt,name=set_count,json=setCount,proto3" json:"set_count,omitempty"`
	VolumeKg      float64                `protobuf:"fixed64,3,opt,name=volume_kg,json=volumeKg,proto3" json:"volume_kg,omitempty"`
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuscleGroupStat) Reset() {
	*x = MuscleGroupStat{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuscleGroupStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuscleGroupStat) ProtoMessage() {}

func (x *MuscleGroupStat) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuscleGroupStat.ProtoReflect.Descriptor instead.
func (*MuscleGroupStat) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *MuscleGroupStat) GetMuscleGroup() string {
	if x != nil {
		return x.MuscleGroup
	}
	return ""
}

func (x *MuscleGroupStat) GetSetCount() int32 {
	if x != nil {
		return x.SetCount
	}
	return 0
}

func (x *MuscleGroupStat) GetVolumeKg() float64 {
	if x != nil {
		return x.VolumeKg
	}
	return 0
}

func (x *MuscleGroupStat) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type GetMuscleGroupStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*MuscleGroupStat     `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMuscleGroupStatsResponse) Reset() {
	*x = GetMuscleGroupStatsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMuscleGroupStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMuscleGroupStatsResponse) ProtoMessage() {}

func (x *GetMuscleGroupStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMuscleGroupStatsResponse.ProtoReflect.Descriptor instead.
func (*GetMuscleGroupStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetMuscleGroupStatsResponse) GetStats() []*MuscleGroupStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetTopExercisesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	DateRange     *DateRange             `protobuf:"bytes,3,opt,name=date_range,json=dateRange,proto3" json:"date_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopExercisesRequest) Reset() {
	*x = GetTopExercisesRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopExercisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopExercisesRequest) ProtoMessage() {}

func (x *GetTopExercisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopExercisesRequest.ProtoReflect.Descriptor instead.
func (*GetTopExercisesRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopExercisesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTopExercisesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopExercisesRequest) GetDateRange() *DateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

type ExerciseRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	ExerciseName  string                 `protobuf:"bytes,2,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	WorkoutCount  int32                  `protobuf:"varint,3,opt,name=workout_count,json=workoutCount,proto3" json:"workout_count,omitempty"`
	LastPerformed string                 `protobuf:"bytes,4,opt,name=last_performed,json=lastPerformed,proto3" json:"last_performed,omitempty"`
	AverageWeight float64                `protobuf:"fixed64,5,opt,name=average_weight,json=averageWeight,proto3" json:"average_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseRecord) Reset() {
	*x = ExerciseRecord{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseRecord) ProtoMessage() {}

func (x *ExerciseRecord) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseRecord.ProtoReflect.Descriptor instead.
func (*ExerciseRecord) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *ExerciseRecord) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *ExerciseRecord) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *ExerciseRecord) GetWorkoutCount() int32 {
	if x != nil {
		return x.WorkoutCount
	}
	return 0
}

func (x *ExerciseRecord) GetLastPerformed() string {
	if x != nil {
		return x.LastPerformed
	}
	return ""
}

func (x *ExerciseRecord) GetAverageWeight() float64 {
	if x != nil {
		return x.AverageWeight
	}
	return 0
}

type GetTopExercisesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercises     []*ExerciseRecord      `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopExercisesResponse) Reset() {
	*x = GetTopExercisesResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopExercisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopExercisesResponse) ProtoMessage() {}

func (x *GetTopExercisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopExercisesResponse.ProtoReflect.Descriptor instead.
func (*GetTopExercisesResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetTopExercisesResponse) GetExercises() []*ExerciseRecord {
	if x != nil {
		return x.Exercises
	}
	return nil
}

type GetExerciseStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExerciseId    string                 `protobuf:"bytes,2,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseStatsRequest) Reset() {
	*x = GetExerciseStatsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseStatsRequest) ProtoMessage() {}

func (x *GetExerciseStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseStatsRequest.ProtoReflect.Descriptor instead.
func (*GetExerciseStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *GetExerciseStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetExerciseStatsRequest) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

type WorkoutExerciseEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutId     string                 `protobuf:"bytes,1,opt,name=workout_id,json=workoutId,proto3" json:"workout_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Reps          int32                  `protobuf:"varint,4,opt,name=reps,proto3" json:"reps,omitempty"`
	OneRm         float64                `protobuf:"fixed64,5,opt,name=one_rm,json=oneRm,proto3" json:"one_rm,omitempty"`
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutExerciseEntry) Reset() {
	*x = WorkoutExerciseEntry{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutExerciseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutExerciseEntry) ProtoMessage() {}

func (x *WorkoutExerciseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutExerciseEntry.ProtoReflect.Descriptor instead.
func (*WorkoutExerciseEntry) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *WorkoutExerciseEntry) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

func (x *WorkoutExerciseEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *WorkoutExerciseEntry) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *WorkoutExerciseEntry) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *WorkoutExerciseEntry) GetOneRm() float64 {
	if x != nil {
		return x.OneRm
	}
	return 0
}

func (x *WorkoutExerciseEntry) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type ExercisePerformance struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	ExerciseId        string                  `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	ExerciseName      string                  `protobuf:"bytes,2,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	HeaviestWeight    float64                 `protobuf:"fixed64,3,opt,name=heaviest_weight,json=heaviestWeight,proto3" json:"heaviest_weight,omitempty"`
	ProjectedOneRm    float64                 `protobuf:"fixed64,4,opt,name=projected_one_rm,json=projectedOneRm,proto3" json:"projected_one_rm,omitempty"`
	BestSetVolume     float64                 `protobuf:"fixed64,5,opt,name=best_set_volume,json=bestSetVolume,proto3" json:"best_set_volume,omitempty"`
	BestSessionVolume float64                 `protobuf:"fixed64,6,opt,name=best_session_volume,json=bestSessionVolume,proto3" json:"best_session_volume,omitempty"`
	MostReps          int32                   `protobuf:"varint,7,opt,name=most_reps,json=mostReps,proto3" json:"most_reps,omitempty"`
	PersonalRecords   []*PersonalRecord       `protobuf:"bytes,8,rep,name=personal_records,json=personalRecords,proto3" json:"personal_records,omitempty"`
	History           []*WorkoutExerciseEntry `protobuf:"bytes,9,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExercisePerformance) Reset() {
	*x = ExercisePerformance{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExercisePerformance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExercisePerformance) ProtoMessage() {}

func (x *ExercisePerformance) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExercisePerformance.ProtoReflect.Descriptor instead.
func (*ExercisePerformance) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *ExercisePerformance) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *ExercisePerformance) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *ExercisePerformance) GetHeaviestWeight() float64 {
	if x != nil {
		return x.HeaviestWeight
	}
	return 0
}

func (x *ExercisePerformance) GetProjectedOneRm() float64 {
	if x != nil {
		return x.ProjectedOneRm
	}
	return 0
}

func (x *ExercisePerformance) GetBestSetVolume() float64 {
	if x != nil {
		return x.BestSetVolume
	}
	return 0
}

func (x *ExercisePerformance) GetBestSessionVolume() float64 {
	if x != nil {
		return x.BestSessionVolume
	}
	return 0
}

func (x *ExercisePerformance) GetMostReps() int32 {
	if x != nil {
		return x.MostReps
	}
	return 0
}

func (x *ExercisePerformance) GetPersonalRecords() []*PersonalRecord {
	if x != nil {
		return x.PersonalRecords
	}
	return nil
}

func (x *ExercisePerformance) GetHistory() []*WorkoutExerciseEntry {
	if x != nil {
		return x.History
	}
	return nil
}

type GetExerciseStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *ExercisePerformance   `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseStatsResponse) Reset() {
	*x = GetExerciseStatsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseStatsResponse) ProtoMessage() {}

func (x *GetExerciseStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseStatsResponse.ProtoReflect.Descriptor instead.
func (*GetExerciseStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *GetExerciseStatsResponse) GetStats() *ExercisePerformance {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ProgressSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CapturedAt    int64                  `protobuf:"varint,2,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	TotalVolumeKg float64                `protobuf:"fixed64,3,opt,name=total_volume_kg,json=totalVolumeKg,proto3" json:"total_volume_kg,omitempty"`
	AverageRpe    float64                `protobuf:"fixed64,4,opt,name=average_rpe,json=averageRpe,proto3" json:"average_rpe,omitempty"`
	WorkoutCount  int32                  `protobuf:"varint,5,opt,name=workout_count,json=workoutCount,proto3" json:"workout_count,omitempty"`
	Prs           []*PersonalRecord      `protobuf:"bytes,6,rep,name=prs,proto3" json:"prs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressSnapshot) Reset() {
	*x = ProgressSnapshot{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressSnapshot) ProtoMessage() {}

func (x *ProgressSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressSnapshot.ProtoReflect.Descriptor instead.
func (*ProgressSnapshot) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *ProgressSnapshot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProgressSnapshot) GetCapturedAt() int64 {
	if x != nil {
		return x.CapturedAt
	}
	return 0
}

func (x *ProgressSnapshot) GetTotalVolumeKg() float64 {
	if x != nil {
		return x.TotalVolumeKg
	}
	return 0
}

func (x *ProgressSnapshot) GetAverageRpe() float64 {
	if x != nil {
		return x.AverageRpe
	}
	return 0
}

func (x *ProgressSnapshot) GetWorkoutCount() int32 {
	if x != nil {
		return x.WorkoutCount
	}
	return 0
}

func (x *ProgressSnapshot) GetPrs() []*PersonalRecord {
	if x != nil {
		return x.Prs
	}
	return nil
}

type PersonalRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	RecordType    string                 `protobuf:"bytes,2,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	AchievedAt    int64                  `protobuf:"varint,4,opt,name=achieved_at,json=achievedAt,proto3" json:"achieved_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalRecord) Reset() {
	*x = PersonalRecord{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalRecord) ProtoMessage() {}

func (x *PersonalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalRecord.ProtoReflect.Descriptor instead.
func (*PersonalRecord) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *PersonalRecord) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *PersonalRecord) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *PersonalRecord) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PersonalRecord) GetAchievedAt() int64 {
	if x != nil {
		return x.AchievedAt
	}
	return 0
}

type GetProgressSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressSnapshotRequest) Reset() {
	*x = GetProgressSnapshotRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressSnapshotRequest) ProtoMessage() {}

func (x *GetProgressSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetProgressSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *GetProgressSnapshotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPersonalRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonalRecordsRequest) Reset() {
	*x = ListPersonalRecordsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonalRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonalRecordsRequest) ProtoMessage() {}

func (x *ListPersonalRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonalRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListPersonalRecordsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *ListPersonalRecordsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPersonalRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*PersonalRecord      `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonalRecordsResponse) Reset() {
	*x = ListPersonalRecordsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonalRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonalRecordsResponse) ProtoMessage() {}

func (x *ListPersonalRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonalRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListPersonalRecordsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *ListPersonalRecordsResponse) GetRecords() []*PersonalRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type RecalculateMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WorkoutId     string                 `protobuf:"bytes,2,opt,name=workout_id,json=workoutId,proto3" json:"workout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecalculateMetricsRequest) Reset() {
	*x = RecalculateMetricsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalculateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalculateMetricsRequest) ProtoMessage() {}

func (x *RecalculateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalculateMetricsRequest.ProtoReflect.Descriptor instead.
func (*RecalculateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *RecalculateMetricsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecalculateMetricsRequest) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

type RecalculateMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheduled     bool                   `protobuf:"varint,1,opt,name=scheduled,proto3" json:"scheduled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecalculateMetricsResponse) Reset() {
	*x = RecalculateMetricsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalculateMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalculateMetricsResponse) ProtoMessage() {}

func (x *RecalculateMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalculateMetricsResponse.ProtoReflect.Descriptor instead.
func (*RecalculateMetricsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{19}
}

func (x *RecalculateMetricsResponse) GetScheduled() bool {
	if x != nil {
		return x.Scheduled
	}
	return false
}

var File_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1canalytics/v1/analytics.proto\x12\x11zenx.analytics.v1\"E\n" +
	"\tDateRange\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"q\n" +
	"\x19GetWorkoutCalendarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12;\n" +
	"\n" +
	"date_range\x18\x02 \x01(\v2\x1c.zenx.analytics.v1.DateRangeR\tdateRange\"f\n" +
	"\x1aGetWorkoutCalendarResponse\x12!\n" +
	"\fworkout_days\x18\x01 \x03(\tR\vworkoutDays\x12%\n" +
	"\x0etotal_workouts\x18\x02 \x01(\x05R\rtotalWorkouts\"r\n" +
	"\x1aGetMuscleGroupStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12;\n" +
	"\n" +
	"date_range\x18\x02 \x01(\v2\x1c.zenx.analytics.v1.DateRangeR\tdateRange\"\x8e\x01\n" +
	"\x0fMuscleGroupStat\x12!\n" +
	"\fmuscle_group\x18\x01 \x01(\tR\vmuscleGroup\x12\x1b\n" +
	"\tset_count\x18\x02 \x01(\x05R\bsetCount\x12\x1b\n" +
	"\tvolume_kg\x18\x03 \x01(\x01R\bvolumeKg\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\"W\n" +
	"\x1bGetMuscleGroupStatsResponse\x128\n" +
	"\x05stats\x18\x01 \x03(\v2\".zenx.analytics.v1.MuscleGroupStatR\x05stats\"\x84\x01\n" +
	"\x16GetTopExercisesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12;\n" +
	"\n" +
	"date_range\x18\x03 \x01(\v2\x1c.zenx.analytics.v1.DateRangeR\tdateRange\"\xc9\x01\n" +
	"\x0eExerciseRecord\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\x12#\n" +
	"\rexercise_name\x18\x02 \x01(\tR\fexerciseName\x12#\n" +
	"\rworkout_count\x18\x03 \x01(\x05R\fworkoutCount\x12%\n" +
	"\x0elast_performed\x18\x04 \x01(\tR\rlastPerformed\x12%\n" +
	"\x0eaverage_weight\x18\x05 \x01(\x01R\raverageWeight\"Z\n" +
	"\x17GetTopExercisesResponse\x12?\n" +
	"\texercises\x18\x01 \x03(\v2!.zenx.analytics.v1.ExerciseRecordR\texercises\"S\n" +
	"\x17GetExerciseStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vexercise_id\x18\x02 \x01(\tR\n" +
	"exerciseId\"\xa4\x01\n" +
	"\x14WorkoutExerciseEntry\x12\x1d\n" +
	"\n" +
	"workout_id\x18\x01 \x01(\tR\tworkoutId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\x12\n" +
	"\x04reps\x18\x04 \x01(\x05R\x04reps\x12\x15\n" +
	"\x06one_rm\x18\x05 \x01(\x01R\x05oneRm\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\"\xb4\x03\n" +
	"\x13ExercisePerformance\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\x12#\n" +
	"\rexercise_name\x18\x02 \x01(\tR\fexerciseName\x12'\n" +
	"\x0fheaviest_weight\x18\x03 \x01(\x01R\x0eheaviestWeight\x12(\n" +
	"\x10projected_one_rm\x18\x04 \x01(\x01R\x0eprojectedOneRm\x12&\n" +
	"\x0fbest_set_volume\x18\x05 \x01(\x01R\rbestSetVolume\x12.\n" +
	"\x13best_session_volume\x18\x06 \x01(\x01R\x11bestSessionVolume\x12\x1b\n" +
	"\tmost_reps\x18\a \x01(\x05R\bmostReps\x12L\n" +
	"\x10personal_records\x18\b \x03(\v2!.zenx.analytics.v1.PersonalRecordR\x0fpersonalRecords\x12A\n" +
	"\ahistory\x18\t \x03(\v2'.zenx.analytics.v1.WorkoutExerciseEntryR\ahistory\"X\n" +
	"\x18GetExerciseStatsResponse\x12<\n" +
	"\x05stats\x18\x01 \x01(\v2&.zenx.analytics.v1.ExercisePerformanceR\x05stats\"\xef\x01\n" +
	"\x10ProgressSnapshot\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcaptured_at\x18\x02 \x01(\x03R\n" +
	"capturedAt\x12&\n" +
	"\x0ftotal_volume_kg\x18\x03 \x01(\x01R\rtotalVolumeKg\x12\x1f\n" +
	"\vaverage_rpe\x18\x04 \x01(\x01R\n" +
	"averageRpe\x12#\n" +
	"\rworkout_count\x18\x05 \x01(\x05R\fworkoutCount\x123\n" +
	"\x03prs\x18\x06 \x03(\v2!.zenx.analytics.v1.PersonalRecordR\x03prs\"\x89\x01\n" +
	"\x0ePersonalRecord\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\x12\x1f\n" +
	"\vrecord_type\x18\x02 \x01(\tR\n" +
	"recordType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1f\n" +
	"\vachieved_at\x18\x04 \x01(\x03R\n" +
	"achievedAt\"5\n" +
	"\x1aGetProgressSnapshotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\x1aListPersonalRecordsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"\x1bListPersonalRecordsResponse\x12;\n" +
	"\arecords\x18\x01 \x03(\v2!.zenx.analytics.v1.PersonalRecordR\arecords\"S\n" +
	"\x19RecalculateMetricsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"workout_id\x18\x02 \x01(\tR\tworkoutId\":\n" +
	"\x1aRecalculateMetricsResponse\x12\x1c\n" +
	"\tscheduled\x18\x01 \x01(\bR\tscheduled2\xa6\x06\n" +
	"\x10AnalyticsService\x12i\n" +
	"\x13GetProgressSnapshot\x12-.zenx.analytics.v1.GetProgressSnapshotRequest\x1a#.zenx.analytics.v1.ProgressSnapshot\x12t\n" +
	"\x13ListPersonalRecords\x12-.zenx.analytics.v1.ListPersonalRecordsRequest\x1a..zenx.analytics.v1.ListPersonalRecordsResponse\x12q\n" +
	"\x12RecalculateMetrics\x12,.zenx.analytics.v1.RecalculateMetricsRequest\x1a-.zenx.analytics.v1.RecalculateMetricsResponse\x12q\n" +
	"\x12GetWorkoutCalendar\x12,.zenx.analytics.v1.GetWorkoutCalendarRequest\x1a-.zenx.analytics.v1.GetWorkoutCalendarResponse\x12t\n" +
	"\x13GetMuscleGroupStats\x12-.zenx.analytics.v1.GetMuscleGroupStatsRequest\x1a..zenx.analytics.v1.GetMuscleGroupStatsResponse\x12h\n" +
	"\x0fGetTopExercises\x12).zenx.analytics.v1.GetTopExercisesRequest\x1a*.zenx.analytics.v1.GetTopExercisesResponse\x12k\n" +
	"\x10GetExerciseStats\x12*.zenx.analytics.v1.GetExerciseStatsRequest\x1a+.zenx.analytics.v1.GetExerciseStatsResponseB8Z6github.com/zenx/backend/proto/analytics/v1;analyticsv1b\x06proto3"

var (
	file_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_analytics_v1_analytics_proto_rawDescData []byte
)

func file_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_analytics_v1_analytics_proto_rawDescData
}

var file_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_analytics_v1_analytics_proto_goTypes = []any{
	(*DateRange)(nil),                   // 0: zenx.analytics.v1.DateRange
	(*GetWorkoutCalendarRequest)(nil),   // 1: zenx.analytics.v1.GetWorkoutCalendarRequest
	(*GetWorkoutCalendarResponse)(nil),  // 2: zenx.analytics.v1.GetWorkoutCalendarResponse
	(*GetMuscleGroupStatsRequest)(nil),  // 3: zenx.analytics.v1.GetMuscleGroupStatsRequest
	(*MuscleGroupStat)(nil),             // 4: zenx.analytics.v1.MuscleGroupStat
	(*GetMuscleGroupStatsResponse)(nil), // 5: zenx.analytics.v1.GetMuscleGroupStatsResponse
	(*GetTopExercisesRequest)(nil),      // 6: zenx.analytics.v1.GetTopExercisesRequest
	(*ExerciseRecord)(nil),              // 7: zenx.analytics.v1.ExerciseRecord
	(*GetTopExercisesResponse)(nil),     // 8: zenx.analytics.v1.GetTopExercisesResponse
	(*GetExerciseStatsRequest)(nil),     // 9: zenx.analytics.v1.GetExerciseStatsRequest
	(*WorkoutExerciseEntry)(nil),        // 10: zenx.analytics.v1.WorkoutExerciseEntry
	(*ExercisePerformance)(nil),         // 11: zenx.analytics.v1.ExercisePerformance
	(*GetExerciseStatsResponse)(nil),    // 12: zenx.analytics.v1.GetExerciseStatsResponse
	(*ProgressSnapshot)(nil),            // 13: zenx.analytics.v1.ProgressSnapshot
	(*PersonalRecord)(nil),              // 14: zenx.analytics.v1.PersonalRecord
	(*GetProgressSnapshotRequest)(nil),  // 15: zenx.analytics.v1.GetProgressSnapshotRequest
	(*ListPersonalRecordsRequest)(nil),  // 16: zenx.analytics.v1.ListPersonalRecordsRequest
	(*ListPersonalRecordsResponse)(nil), // 17: zenx.analytics.v1.ListPersonalRecordsResponse
	(*RecalculateMetricsRequest)(nil),   // 18: zenx.analytics.v1.RecalculateMetricsRequest
	(*RecalculateMetricsResponse)(nil),  // 19: zenx.analytics.v1.RecalculateMetricsResponse
}
var file_analytics_v1_analytics_proto_depIdxs = []int32{
	0,  // 0: zenx.analytics.v1.GetWorkoutCalendarRequest.date_range:type_name -> zenx.analytics.v1.DateRange
	0,  // 1: zenx.analytics.v1.GetMuscleGroupStatsRequest.date_range:type_name -> zenx.analytics.v1.DateRange
	4,  // 2: zenx.analytics.v1.GetMuscleGroupStatsResponse.stats:type_name -> zenx.analytics.v1.MuscleGroupStat
	0,  // 3: zenx.analytics.v1.GetTopExercisesRequest.date_range:type_name -> zenx.analytics.v1.DateRange
	7,  // 4: zenx.analytics.v1.GetTopExercisesResponse.exercises:type_name -> zenx.analytics.v1.ExerciseRecord
	14, // 5: zenx.analytics.v1.ExercisePerformance.personal_records:type_name -> zenx.analytics.v1.PersonalRecord
	10, // 6: zenx.analytics.v1.ExercisePerformance.history:type_name -> zenx.analytics.v1.WorkoutExerciseEntry
	11, // 7: zenx.analytics.v1.GetExerciseStatsResponse.stats:type_name -> zenx.analytics.v1.ExercisePerformance
	14, // 8: zenx.analytics.v1.ProgressSnapshot.prs:type_name -> zenx.analytics.v1.PersonalRecord
	14, // 9: zenx.analytics.v1.ListPersonalRecordsResponse.records:type_name -> zenx.analytics.v1.PersonalRecord
	15, // 10: zenx.analytics.v1.AnalyticsService.GetProgressSnapshot:input_type -> zenx.analytics.v1.GetProgressSnapshotRequest
	16, // 11: zenx.analytics.v1.AnalyticsService.ListPersonalRecords:input_type -> zenx.analytics.v1.ListPersonalRecordsRequest
	18, // 12: zenx.analytics.v1.AnalyticsService.RecalculateMetrics:input_type -> zenx.analytics.v1.RecalculateMetricsRequest
	1,  // 13: zenx.analytics.v1.AnalyticsService.GetWorkoutCalendar:input_type -> zenx.analytics.v1.GetWorkoutCalendarRequest
	3,  // 14: zenx.analytics.v1.AnalyticsService.GetMuscleGroupStats:input_type -> zenx.analytics.v1.GetMuscleGroupStatsRequest
	6,  // 15: zenx.analytics.v1.AnalyticsService.GetTopExercises:input_type -> zenx.analytics.v1.GetTopExercisesRequest
	9,  // 16: zenx.analytics.v1.AnalyticsService.GetExerciseStats:input_type -> zenx.analytics.v1.GetExerciseStatsRequest
	13, // 17: zenx.analytics.v1.AnalyticsService.GetProgressSnapshot:output_type -> zenx.analytics.v1.ProgressSnapshot
	17, // 18: zenx.analytics.v1.AnalyticsService.ListPersonalRecords:output_type -> zenx.analytics.v1.ListPersonalRecordsResponse
	19, // 19: zenx.analytics.v1.AnalyticsService.RecalculateMetrics:output_type -> zenx.analytics.v1.RecalculateMetricsResponse
	2,  // 20: zenx.analytics.v1.AnalyticsService.GetWorkoutCalendar:output_type -> zenx.analytics.v1.GetWorkoutCalendarResponse
	5,  // 21: zenx.analytics.v1.AnalyticsService.GetMuscleGroupStats:output_type -> zenx.analytics.v1.GetMuscleGroupStatsResponse
	8,  // 22: zenx.analytics.v1.AnalyticsService.GetTopExercises:output_type -> zenx.analytics.v1.GetTopExercisesResponse
	12, // 23: zenx.analytics.v1.AnalyticsService.GetExerciseStats:output_type -> zenx.analytics.v1.GetExerciseStatsResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_analytics_v1_analytics_proto_init() }
func file_analytics_v1_analytics_proto_init() {
	if File_analytics_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_analytics_v1_analytics_proto = out.File
	file_analytics_v1_analytics_proto_goTypes = nil
	file_analytics_v1_analytics_proto_depIdxs = nil
}
