// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notification/v1/notification.proto

package notificationv1

import (
	v1 "github.com/zenx/backend/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueueNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Template      string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ScheduledFor  int64                  `protobuf:"varint,4,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueNotificationRequest) Reset() {
	*x = EnqueueNotificationRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueNotificationRequest) ProtoMessage() {}

func (x *EnqueueNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueNotificationRequest.ProtoReflect.Descriptor instead.
func (*EnqueueNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnqueueNotificationRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *EnqueueNotificationRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EnqueueNotificationRequest) GetScheduledFor() int64 {
	if x != nil {
		return x.ScheduledFor
	}
	return 0
}

type EnqueueNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueueNotificationResponse) Reset() {
	*x = EnqueueNotificationResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueNotificationResponse) ProtoMessage() {}

func (x *EnqueueNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueNotificationResponse.ProtoReflect.Descriptor instead.
func (*EnqueueNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type Preference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preference) Reset() {
	*x = Preference{}
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preference) ProtoMessage() {}

func (x *Preference) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preference.ProtoReflect.Descriptor instead.
func (*Preference) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *Preference) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Preference) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Preference) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdatePreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preference    *Preference            `protobuf:"bytes,1,opt,name=preference,proto3" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferenceRequest) Reset() {
	*x = UpdatePreferenceRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferenceRequest) ProtoMessage() {}

func (x *UpdatePreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferenceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferenceRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePreferenceRequest) GetPreference() *Preference {
	if x != nil {
		return x.Preference
	}
	return nil
}

type ListPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPreferencesRequest) Reset() {
	*x = ListPreferencesRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPreferencesRequest) ProtoMessage() {}

func (x *ListPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPreferencesRequest.ProtoReflect.Descriptor instead.
func (*ListPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ListPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preferences   []*Preference          `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPreferencesResponse) Reset() {
	*x = ListPreferencesResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPreferencesResponse) ProtoMessage() {}

func (x *ListPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPreferencesResponse.ProtoReflect.Descriptor instead.
func (*ListPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ListPreferencesResponse) GetPreferences() []*Preference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Template      string                 `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ScheduledFor  int64                  `protobuf:"varint,7,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	SentAt        int64                  `protobuf:"varint,8,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Notification) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Notification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Notification) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Notification) GetScheduledFor() int64 {
	if x != nil {
		return x.ScheduledFor
	}
	return 0
}

func (x *Notification) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *ListNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListNotificationsRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListNotificationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type MarkNotificationReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkNotificationReadRequest) Reset() {
	*x = MarkNotificationReadRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadRequest) ProtoMessage() {}

func (x *MarkNotificationReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *MarkNotificationReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *MarkNotificationReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x14zenx.notification.v1\x1a\x16common/v1/common.proto\"\xff\x01\n" +
	"\x1aEnqueueNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12N\n" +
	"\x04data\x18\x03 \x03(\v2:.zenx.notification.v1.EnqueueNotificationRequest.DataEntryR\x04data\x12#\n" +
	"\rscheduled_for\x18\x04 \x01(\x03R\fscheduledFor\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x1bEnqueueNotificationResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"Y\n" +
	"\n" +
	"Preference\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"[\n" +
	"\x17UpdatePreferenceRequest\x12@\n" +
	"\n" +
	"preference\x18\x01 \x01(\v2 .zenx.notification.v1.PreferenceR\n" +
	"preference\"1\n" +
	"\x16ListPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"]\n" +
	"\x17ListPreferencesResponse\x12B\n" +
	"\vpreferences\x18\x01 \x03(\v2 .zenx.notification.v1.PreferenceR\vpreferences\"\xc3\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\x12@\n" +
	"\x04data\x18\x04 \x03(\v2,.zenx.notification.v1.Notification.DataEntryR\x04data\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12#\n" +
	"\rscheduled_for\x18\a \x01(\x03R\fscheduledFor\x12\x17\n" +
	"\asent_at\x18\b \x01(\x03R\x06sentAt\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x18ListNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.zenx.common.v1.PaginationR\n" +
	"pagination\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x86\x01\n" +
	"\x19ListNotificationsResponse\x12H\n" +
	"\rnotifications\x18\x01 \x03(\v2\".zenx.notification.v1.NotificationR\rnotifications\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"_\n" +
	"\x1bMarkNotificationReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2\xcb\x04\n" +
	"\x13NotificationService\x12z\n" +
	"\x13EnqueueNotification\x120.zenx.notification.v1.EnqueueNotificationRequest\x1a1.zenx.notification.v1.EnqueueNotificationResponse\x12c\n" +
	"\x10UpdatePreference\x12-.zenx.notification.v1.UpdatePreferenceRequest\x1a .zenx.notification.v1.Preference\x12n\n" +
	"\x0fListPreferences\x12,.zenx.notification.v1.ListPreferencesRequest\x1a-.zenx.notification.v1.ListPreferencesResponse\x12t\n" +
	"\x11ListNotifications\x12..zenx.notification.v1.ListNotificationsRequest\x1a/.zenx.notification.v1.ListNotificationsResponse\x12m\n" +
	"\x14MarkNotificationRead\x121.zenx.notification.v1.MarkNotificationReadRequest\x1a\".zenx.notification.v1.NotificationB>Z<github.com/zenx/backend/proto/notification/v1;notificationv1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_notification_v1_notification_proto_goTypes = []any{
	(*EnqueueNotificationRequest)(nil),  // 0: zenx.notification.v1.EnqueueNotificationRequest
	(*EnqueueNotificationResponse)(nil), // 1: zenx.notification.v1.EnqueueNotificationResponse
	(*Preference)(nil),                  // 2: zenx.notification.v1.Preference
	(*UpdatePreferenceRequest)(nil),     // 3: zenx.notification.v1.UpdatePreferenceRequest
	(*ListPreferencesRequest)(nil),      // 4: zenx.notification.v1.ListPreferencesRequest
	(*ListPreferencesResponse)(nil),     // 5: zenx.notification.v1.ListPreferencesResponse
	(*Notification)(nil),                // 6: zenx.notification.v1.Notification
	(*ListNotificationsRequest)(nil),    // 7: zenx.notification.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),   // 8: zenx.notification.v1.ListNotificationsResponse
	(*MarkNotificationReadRequest)(nil), // 9: zenx.notification.v1.MarkNotificationReadRequest
	nil,                                 // 10: zenx.notification.v1.EnqueueNotificationRequest.DataEntry
	nil,                                 // 11: zenx.notification.v1.Notification.DataEntry
	(*v1.Pagination)(nil),               // 12: zenx.common.v1.Pagination
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	10, // 0: zenx.notification.v1.EnqueueNotificationRequest.data:type_name -> zenx.notification.v1.EnqueueNotificationRequest.DataEntry
	2,  // 1: zenx.notification.v1.UpdatePreferenceRequest.preference:type_name -> zenx.notification.v1.Preference
	2,  // 2: zenx.notification.v1.ListPreferencesResponse.preferences:type_name -> zenx.notification.v1.Preference
	11, // 3: zenx.notification.v1.Notification.data:type_name -> zenx.notification.v1.Notification.DataEntry
	12, // 4: zenx.notification.v1.ListNotificationsRequest.pagination:type_name -> zenx.common.v1.Pagination
	6,  // 5: zenx.notification.v1.ListNotificationsResponse.notifications:type_name -> zenx.notification.v1.Notification
	0,  // 6: zenx.notification.v1.NotificationService.EnqueueNotification:input_type -> zenx.notification.v1.EnqueueNotificationRequest
	3,  // 7: zenx.notification.v1.NotificationService.UpdatePreference:input_type -> zenx.notification.v1.UpdatePreferenceRequest
	4,  // 8: zenx.notification.v1.NotificationService.ListPreferences:input_type -> zenx.notification.v1.ListPreferencesRequest
	7,  // 9: zenx.notification.v1.NotificationService.ListNotifications:input_type -> zenx.notification.v1.ListNotificationsRequest
	9,  // 10: zenx.notification.v1.NotificationService.MarkNotificationRead:input_type -> zenx.notification.v1.MarkNotificationReadRequest
	1,  // 11: zenx.notification.v1.NotificationService.EnqueueNotification:output_type -> zenx.notification.v1.EnqueueNotificationResponse
	2,  // 12: zenx.notification.v1.NotificationService.UpdatePreference:output_type -> zenx.notification.v1.Preference
	5,  // 13: zenx.notification.v1.NotificationService.ListPreferences:output_type -> zenx.notification.v1.ListPreferencesResponse
	8,  // 14: zenx.notification.v1.NotificationService.ListNotifications:output_type -> zenx.notification.v1.ListNotificationsResponse
	6,  // 15: zenx.notification.v1.NotificationService.MarkNotificationRead:output_type -> zenx.notification.v1.Notification
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
