// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: workout/v1/workout.proto

package workoutv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/zenx/backend/proto/workout/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkoutServiceName is the fully-qualified name of the WorkoutService service.
	WorkoutServiceName = "zenx.workout.v1.WorkoutService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkoutServiceCreateWorkoutProcedure is the fully-qualified name of the WorkoutService's
	// CreateWorkout RPC.
	WorkoutServiceCreateWorkoutProcedure = "/zenx.workout.v1.WorkoutService/CreateWorkout"
	// WorkoutServiceGetWorkoutProcedure is the fully-qualified name of the WorkoutService's GetWorkout
	// RPC.
	WorkoutServiceGetWorkoutProcedure = "/zenx.workout.v1.WorkoutService/GetWorkout"
	// WorkoutServiceListWorkoutsProcedure is the fully-qualified name of the WorkoutService's
	// ListWorkouts RPC.
	WorkoutServiceListWorkoutsProcedure = "/zenx.workout.v1.WorkoutService/ListWorkouts"
	// WorkoutServiceListFeedPostsProcedure is the fully-qualified name of the WorkoutService's
	// ListFeedPosts RPC.
	WorkoutServiceListFeedPostsProcedure = "/zenx.workout.v1.WorkoutService/ListFeedPosts"
	// WorkoutServiceGetFeedPostProcedure is the fully-qualified name of the WorkoutService's
	// GetFeedPost RPC.
	WorkoutServiceGetFeedPostProcedure = "/zenx.workout.v1.WorkoutService/GetFeedPost"
	// WorkoutServiceToggleFeedLikeProcedure is the fully-qualified name of the WorkoutService's
	// ToggleFeedLike RPC.
	WorkoutServiceToggleFeedLikeProcedure = "/zenx.workout.v1.WorkoutService/ToggleFeedLike"
	// WorkoutServiceAddFeedCommentProcedure is the fully-qualified name of the WorkoutService's
	// AddFeedComment RPC.
	WorkoutServiceAddFeedCommentProcedure = "/zenx.workout.v1.WorkoutService/AddFeedComment"
	// WorkoutServiceListFeedCommentsProcedure is the fully-qualified name of the WorkoutService's
	// ListFeedComments RPC.
	WorkoutServiceListFeedCommentsProcedure = "/zenx.workout.v1.WorkoutService/ListFeedComments"
	// WorkoutServiceStreamWorkoutProcedure is the fully-qualified name of the WorkoutService's
	// StreamWorkout RPC.
	WorkoutServiceStreamWorkoutProcedure = "/zenx.workout.v1.WorkoutService/StreamWorkout"
)

// WorkoutServiceClient is a client for the zenx.workout.v1.WorkoutService service.
type WorkoutServiceClient interface {
	CreateWorkout(context.Context, *connect.Request[v1.CreateWorkoutRequest]) (*connect.Response[v1.CreateWorkoutResponse], error)
	GetWorkout(context.Context, *connect.Request[v1.GetWorkoutRequest]) (*connect.Response[v1.GetWorkoutResponse], error)
	ListWorkouts(context.Context, *connect.Request[v1.ListWorkoutsRequest]) (*connect.Response[v1.ListWorkoutsResponse], error)
	ListFeedPosts(context.Context, *connect.Request[v1.ListFeedPostsRequest]) (*connect.Response[v1.ListFeedPostsResponse], error)
	GetFeedPost(context.Context, *connect.Request[v1.GetFeedPostRequest]) (*connect.Response[v1.FeedPost], error)
	ToggleFeedLike(context.Context, *connect.Request[v1.ToggleFeedLikeRequest]) (*connect.Response[v1.ToggleFeedLikeResponse], error)
	AddFeedComment(context.Context, *connect.Request[v1.AddFeedCommentRequest]) (*connect.Response[v1.FeedComment], error)
	ListFeedComments(context.Context, *connect.Request[v1.ListFeedCommentsRequest]) (*connect.Response[v1.ListFeedCommentsResponse], error)
	StreamWorkout(context.Context, *connect.Request[v1.StreamWorkoutRequest]) (*connect.ServerStreamForClient[v1.WorkoutUpdate], error)
}

// NewWorkoutServiceClient constructs a client for the zenx.workout.v1.WorkoutService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkoutServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkoutServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workoutServiceMethods := v1.File_workout_v1_workout_proto.Services().ByName("WorkoutService").Methods()
	return &workoutServiceClient{
		createWorkout: connect.NewClient[v1.CreateWorkoutRequest, v1.CreateWorkoutResponse](
			httpClient,
			baseURL+WorkoutServiceCreateWorkoutProcedure,
			connect.WithSchema(workoutServiceMethods.ByName("CreateWorkout")),
			connect.WithClientOptions(opts...),
		),
		getWorkout: connect.NewClient[v1.GetWorkoutRequest, v1.GetWorkoutResponse](
			httpClient,
			baseURL+WorkoutServiceGetWorkoutProcedure,
			connect.WithSchema(workoutServiceMethods.ByName("GetWorkout")),
			connect.WithClientOptions(opts...),
		),
		listWorkouts: connect.NewClient[v1.ListWorkoutsRequest, v1.ListWorkoutsResponse](
			httpClient,
			baseURL+WorkoutServiceListWorkoutsProcedure,
			connect.WithSchema(workoutServiceMethods.ByName("ListWorkouts")),
			connect.WithClientOptions(opts...),
		),
		listFeedPosts: connect.NewClient[v1.ListFeedPostsRequest, v1.ListFeedPostsResponse](
			httpClient,
			baseURL+WorkoutServiceListFeedPostsProcedure,
			connect.WithSchema(workoutServiceMethods.ByName("ListFeedPosts")),
			connect.WithClientOptions(opts...),
		),
		getFeedPost: connect.NewClient[v1.GetFeedPostRequest, v1.FeedPost](
			httpClient,
			baseURL+WorkoutServiceGetFeedPostProcedure,
			connect.WithSchema(workoutServiceMethods.ByName("GetFeedPost")),
			connect.WithClientOptions(opts...),
		),
		toggleFeedLike: connect.NewClient[v1.ToggleFeedLikeRequest, v1.ToggleFeedLikeResponse](
			httpClient,
			baseURL+WorkoutServiceToggleFeedLikeProcedure,
			connect.WithSchema(workoutServiceMethods.ByName("ToggleFeedLike")),
			connect.WithClientOptions(opts...),
		),
		addFeedComment: connect.NewClient[v1.AddFeedCommentRequest, v1.FeedComment](
			httpClient,
			baseURL+WorkoutServiceAddFeedCommentProcedure,
			connect.WithSchema(workoutServiceMethods.ByName("AddFeedComment")),
			connect.WithClientOptions(opts...),
		),
		listFeedComments: connect.NewClient[v1.ListFeedCommentsRequest, v1.ListFeedCommentsResponse](
			httpClient,
			baseURL+WorkoutServiceListFeedCommentsProcedure,
			connect.WithSchema(workoutServiceMethods.ByName("ListFeedComments")),
			connect.WithClientOptions(opts...),
		),
		streamWorkout: connect.NewClient[v1.StreamWorkoutRequest, v1.WorkoutUpdate](
			httpClient,
			baseURL+WorkoutServiceStreamWorkoutProcedure,
			connect.WithSchema(workoutServiceMethods.ByName("StreamWorkout")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workoutServiceClient implements WorkoutServiceClient.
type workoutServiceClient struct {
	createWorkout    *connect.Client[v1.CreateWorkoutRequest, v1.CreateWorkoutResponse]
	getWorkout       *connect.Client[v1.GetWorkoutRequest, v1.GetWorkoutResponse]
	listWorkouts     *connect.Client[v1.ListWorkoutsRequest, v1.ListWorkoutsResponse]
	listFeedPosts    *connect.Client[v1.ListFeedPostsRequest, v1.ListFeedPostsResponse]
	getFeedPost      *connect.Client[v1.GetFeedPostRequest, v1.FeedPost]
	toggleFeedLike   *connect.Client[v1.ToggleFeedLikeRequest, v1.ToggleFeedLikeResponse]
	addFeedComment   *connect.Client[v1.AddFeedCommentRequest, v1.FeedComment]
	listFeedComments *connect.Client[v1.ListFeedCommentsRequest, v1.ListFeedCommentsResponse]
	streamWorkout    *connect.Client[v1.StreamWorkoutRequest, v1.WorkoutUpdate]
}

// CreateWorkout calls zenx.workout.v1.WorkoutService.CreateWorkout.
func (c *workoutServiceClient) CreateWorkout(ctx context.Context, req *connect.Request[v1.CreateWorkoutRequest]) (*connect.Response[v1.CreateWorkoutResponse], error) {
	return c.createWorkout.CallUnary(ctx, req)
}

// GetWorkout calls zenx.workout.v1.WorkoutService.GetWorkout.
func (c *workoutServiceClient) GetWorkout(ctx context.Context, req *connect.Request[v1.GetWorkoutRequest]) (*connect.Response[v1.GetWorkoutResponse], error) {
	return c.getWorkout.CallUnary(ctx, req)
}

// ListWorkouts calls zenx.workout.v1.WorkoutService.ListWorkouts.
func (c *workoutServiceClient) ListWorkouts(ctx context.Context, req *connect.Request[v1.ListWorkoutsRequest]) (*connect.Response[v1.ListWorkoutsResponse], error) {
	return c.listWorkouts.CallUnary(ctx, req)
}

// ListFeedPosts calls zenx.workout.v1.WorkoutService.ListFeedPosts.
func (c *workoutServiceClient) ListFeedPosts(ctx context.Context, req *connect.Request[v1.ListFeedPostsRequest]) (*connect.Response[v1.ListFeedPostsResponse], error) {
	return c.listFeedPosts.CallUnary(ctx, req)
}

// GetFeedPost calls zenx.workout.v1.WorkoutService.GetFeedPost.
func (c *workoutServiceClient) GetFeedPost(ctx context.Context, req *connect.Request[v1.GetFeedPostRequest]) (*connect.Response[v1.FeedPost], error) {
	return c.getFeedPost.CallUnary(ctx, req)
}

// ToggleFeedLike calls zenx.workout.v1.WorkoutService.ToggleFeedLike.
func (c *workoutServiceClient) ToggleFeedLike(ctx context.Context, req *connect.Request[v1.ToggleFeedLikeRequest]) (*connect.Response[v1.ToggleFeedLikeResponse], error) {
	return c.toggleFeedLike.CallUnary(ctx, req)
}

// AddFeedComment calls zenx.workout.v1.WorkoutService.AddFeedComment.
func (c *workoutServiceClient) AddFeedComment(ctx context.Context, req *connect.Request[v1.AddFeedCommentRequest]) (*connect.Response[v1.FeedComment], error) {
	return c.addFeedComment.CallUnary(ctx, req)
}

// ListFeedComments calls zenx.workout.v1.WorkoutService.ListFeedComments.
func (c *workoutServiceClient) ListFeedComments(ctx context.Context, req *connect.Request[v1.ListFeedCommentsRequest]) (*connect.Response[v1.ListFeedCommentsResponse], error) {
	return c.listFeedComments.CallUnary(ctx, req)
}

// StreamWorkout calls zenx.workout.v1.WorkoutService.StreamWorkout.
func (c *workoutServiceClient) StreamWorkout(ctx context.Context, req *connect.Request[v1.StreamWorkoutRequest]) (*connect.ServerStreamForClient[v1.WorkoutUpdate], error) {
	return c.streamWorkout.CallServerStream(ctx, req)
}

// WorkoutServiceHandler is an implementation of the zenx.workout.v1.WorkoutService service.
type WorkoutServiceHandler interface {
	CreateWorkout(context.Context, *connect.Request[v1.CreateWorkoutRequest]) (*connect.Response[v1.CreateWorkoutResponse], error)
	GetWorkout(context.Context, *connect.Request[v1.GetWorkoutRequest]) (*connect.Response[v1.GetWorkoutResponse], error)
	ListWorkouts(context.Context, *connect.Request[v1.ListWorkoutsRequest]) (*connect.Response[v1.ListWorkoutsResponse], error)
	ListFeedPosts(context.Context, *connect.Request[v1.ListFeedPostsRequest]) (*connect.Response[v1.ListFeedPostsResponse], error)
	GetFeedPost(context.Context, *connect.Request[v1.GetFeedPostRequest]) (*connect.Response[v1.FeedPost], error)
	ToggleFeedLike(context.Context, *connect.Request[v1.ToggleFeedLikeRequest]) (*connect.Response[v1.ToggleFeedLikeResponse], error)
	AddFeedComment(context.Context, *connect.Request[v1.AddFeedCommentRequest]) (*connect.Response[v1.FeedComment], error)
	ListFeedComments(context.Context, *connect.Request[v1.ListFeedCommentsRequest]) (*connect.Response[v1.ListFeedCommentsResponse], error)
	StreamWorkout(context.Context, *connect.Request[v1.StreamWorkoutRequest], *connect.ServerStream[v1.WorkoutUpdate]) error
}

// NewWorkoutServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkoutServiceHandler(svc WorkoutServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workoutServiceMethods := v1.File_workout_v1_workout_proto.Services().ByName("WorkoutService").Methods()
	workoutServiceCreateWorkoutHandler := connect.NewUnaryHandler(
		WorkoutServiceCreateWorkoutProcedure,
		svc.CreateWorkout,
		connect.WithSchema(workoutServiceMethods.ByName("CreateWorkout")),
		connect.WithHandlerOptions(opts...),
	)
	workoutServiceGetWorkoutHandler := connect.NewUnaryHandler(
		WorkoutServiceGetWorkoutProcedure,
		svc.GetWorkout,
		connect.WithSchema(workoutServiceMethods.ByName("GetWorkout")),
		connect.WithHandlerOptions(opts...),
	)
	workoutServiceListWorkoutsHandler := connect.NewUnaryHandler(
		WorkoutServiceListWorkoutsProcedure,
		svc.ListWorkouts,
		connect.WithSchema(workoutServiceMethods.ByName("ListWorkouts")),
		connect.WithHandlerOptions(opts...),
	)
	workoutServiceListFeedPostsHandler := connect.NewUnaryHandler(
		WorkoutServiceListFeedPostsProcedure,
		svc.ListFeedPosts,
		connect.WithSchema(workoutServiceMethods.ByName("ListFeedPosts")),
		connect.WithHandlerOptions(opts...),
	)
	workoutServiceGetFeedPostHandler := connect.NewUnaryHandler(
		WorkoutServiceGetFeedPostProcedure,
		svc.GetFeedPost,
		connect.WithSchema(workoutServiceMethods.ByName("GetFeedPost")),
		connect.WithHandlerOptions(opts...),
	)
	workoutServiceToggleFeedLikeHandler := connect.NewUnaryHandler(
		WorkoutServiceToggleFeedLikeProcedure,
		svc.ToggleFeedLike,
		connect.WithSchema(workoutServiceMethods.ByName("ToggleFeedLike")),
		connect.WithHandlerOptions(opts...),
	)
	workoutServiceAddFeedCommentHandler := connect.NewUnaryHandler(
		WorkoutServiceAddFeedCommentProcedure,
		svc.AddFeedComment,
		connect.WithSchema(workoutServiceMethods.ByName("AddFeedComment")),
		connect.WithHandlerOptions(opts...),
	)
	workoutServiceListFeedCommentsHandler := connect.NewUnaryHandler(
		WorkoutServiceListFeedCommentsProcedure,
		svc.ListFeedComments,
		connect.WithSchema(workoutServiceMethods.ByName("ListFeedComments")),
		connect.WithHandlerOptions(opts...),
	)
	workoutServiceStreamWorkoutHandler := connect.NewServerStreamHandler(
		WorkoutServiceStreamWorkoutProcedure,
		svc.StreamWorkout,
		connect.WithSchema(workoutServiceMethods.ByName("StreamWorkout")),
		connect.WithHandlerOptions(opts...),
	)
	return "/zenx.workout.v1.WorkoutService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkoutServiceCreateWorkoutProcedure:
			workoutServiceCreateWorkoutHandler.ServeHTTP(w, r)
		case WorkoutServiceGetWorkoutProcedure:
			workoutServiceGetWorkoutHandler.ServeHTTP(w, r)
		case WorkoutServiceListWorkoutsProcedure:
			workoutServiceListWorkoutsHandler.ServeHTTP(w, r)
		case WorkoutServiceListFeedPostsProcedure:
			workoutServiceListFeedPostsHandler.ServeHTTP(w, r)
		case WorkoutServiceGetFeedPostProcedure:
			workoutServiceGetFeedPostHandler.ServeHTTP(w, r)
		case WorkoutServiceToggleFeedLikeProcedure:
			workoutServiceToggleFeedLikeHandler.ServeHTTP(w, r)
		case WorkoutServiceAddFeedCommentProcedure:
			workoutServiceAddFeedCommentHandler.ServeHTTP(w, r)
		case WorkoutServiceListFeedCommentsProcedure:
			workoutServiceListFeedCommentsHandler.ServeHTTP(w, r)
		case WorkoutServiceStreamWorkoutProcedure:
			workoutServiceStreamWorkoutHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkoutServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkoutServiceHandler struct{}

func (UnimplementedWorkoutServiceHandler) CreateWorkout(context.Context, *connect.Request[v1.CreateWorkoutRequest]) (*connect.Response[v1.CreateWorkoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.workout.v1.WorkoutService.CreateWorkout is not implemented"))
}

func (UnimplementedWorkoutServiceHandler) GetWorkout(context.Context, *connect.Request[v1.GetWorkoutRequest]) (*connect.Response[v1.GetWorkoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.workout.v1.WorkoutService.GetWorkout is not implemented"))
}

func (UnimplementedWorkoutServiceHandler) ListWorkouts(context.Context, *connect.Request[v1.ListWorkoutsRequest]) (*connect.Response[v1.ListWorkoutsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.workout.v1.WorkoutService.ListWorkouts is not implemented"))
}

func (UnimplementedWorkoutServiceHandler) ListFeedPosts(context.Context, *connect.Request[v1.ListFeedPostsRequest]) (*connect.Response[v1.ListFeedPostsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.workout.v1.WorkoutService.ListFeedPosts is not implemented"))
}

func (UnimplementedWorkoutServiceHandler) GetFeedPost(context.Context, *connect.Request[v1.GetFeedPostRequest]) (*connect.Response[v1.FeedPost], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.workout.v1.WorkoutService.GetFeedPost is not implemented"))
}

func (UnimplementedWorkoutServiceHandler) ToggleFeedLike(context.Context, *connect.Request[v1.ToggleFeedLikeRequest]) (*connect.Response[v1.ToggleFeedLikeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.workout.v1.WorkoutService.ToggleFeedLike is not implemented"))
}

func (UnimplementedWorkoutServiceHandler) AddFeedComment(context.Context, *connect.Request[v1.AddFeedCommentRequest]) (*connect.Response[v1.FeedComment], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.workout.v1.WorkoutService.AddFeedComment is not implemented"))
}

func (UnimplementedWorkoutServiceHandler) ListFeedComments(context.Context, *connect.Request[v1.ListFeedCommentsRequest]) (*connect.Response[v1.ListFeedCommentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.workout.v1.WorkoutService.ListFeedComments is not implemented"))
}

func (UnimplementedWorkoutServiceHandler) StreamWorkout(context.Context, *connect.Request[v1.StreamWorkoutRequest], *connect.ServerStream[v1.WorkoutUpdate]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("zenx.workout.v1.WorkoutService.StreamWorkout is not implemented"))
}
