// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: workout/v1/workout.proto

package workoutv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkoutService_CreateWorkout_FullMethodName    = "/zenx.workout.v1.WorkoutService/CreateWorkout"
	WorkoutService_GetWorkout_FullMethodName       = "/zenx.workout.v1.WorkoutService/GetWorkout"
	WorkoutService_ListWorkouts_FullMethodName     = "/zenx.workout.v1.WorkoutService/ListWorkouts"
	WorkoutService_ListFeedPosts_FullMethodName    = "/zenx.workout.v1.WorkoutService/ListFeedPosts"
	WorkoutService_GetFeedPost_FullMethodName      = "/zenx.workout.v1.WorkoutService/GetFeedPost"
	WorkoutService_ToggleFeedLike_FullMethodName   = "/zenx.workout.v1.WorkoutService/ToggleFeedLike"
	WorkoutService_AddFeedComment_FullMethodName   = "/zenx.workout.v1.WorkoutService/AddFeedComment"
	WorkoutService_ListFeedComments_FullMethodName = "/zenx.workout.v1.WorkoutService/ListFeedComments"
	WorkoutService_StreamWorkout_FullMethodName    = "/zenx.workout.v1.WorkoutService/StreamWorkout"
)

// WorkoutServiceClient is the client API for WorkoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkoutServiceClient interface {
	CreateWorkout(ctx context.Context, in *CreateWorkoutRequest, opts ...grpc.CallOption) (*CreateWorkoutResponse, error)
	GetWorkout(ctx context.Context, in *GetWorkoutRequest, opts ...grpc.CallOption) (*GetWorkoutResponse, error)
	ListWorkouts(ctx context.Context, in *ListWorkoutsRequest, opts ...grpc.CallOption) (*ListWorkoutsResponse, error)
	ListFeedPosts(ctx context.Context, in *ListFeedPostsRequest, opts ...grpc.CallOption) (*ListFeedPostsResponse, error)
	GetFeedPost(ctx context.Context, in *GetFeedPostRequest, opts ...grpc.CallOption) (*FeedPost, error)
	ToggleFeedLike(ctx context.Context, in *ToggleFeedLikeRequest, opts ...grpc.CallOption) (*ToggleFeedLikeResponse, error)
	AddFeedComment(ctx context.Context, in *AddFeedCommentRequest, opts ...grpc.CallOption) (*FeedComment, error)
	ListFeedComments(ctx context.Context, in *ListFeedCommentsRequest, opts ...grpc.CallOption) (*ListFeedCommentsResponse, error)
	StreamWorkout(ctx context.Context, in *StreamWorkoutRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkoutUpdate], error)
}

type workoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkoutServiceClient(cc grpc.ClientConnInterface) WorkoutServiceClient {
	return &workoutServiceClient{cc}
}

func (c *workoutServiceClient) CreateWorkout(ctx context.Context, in *CreateWorkoutRequest, opts ...grpc.CallOption) (*CreateWorkoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkoutResponse)
	err := c.cc.Invoke(ctx, WorkoutService_CreateWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetWorkout(ctx context.Context, in *GetWorkoutRequest, opts ...grpc.CallOption) (*GetWorkoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkoutResponse)
	err := c.cc.Invoke(ctx, WorkoutService_GetWorkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) ListWorkouts(ctx context.Context, in *ListWorkoutsRequest, opts ...grpc.CallOption) (*ListWorkoutsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkoutsResponse)
	err := c.cc.Invoke(ctx, WorkoutService_ListWorkouts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) ListFeedPosts(ctx context.Context, in *ListFeedPostsRequest, opts ...grpc.CallOption) (*ListFeedPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedPostsResponse)
	err := c.cc.Invoke(ctx, WorkoutService_ListFeedPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) GetFeedPost(ctx context.Context, in *GetFeedPostRequest, opts ...grpc.CallOption) (*FeedPost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedPost)
	err := c.cc.Invoke(ctx, WorkoutService_GetFeedPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) ToggleFeedLike(ctx context.Context, in *ToggleFeedLikeRequest, opts ...grpc.CallOption) (*ToggleFeedLikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleFeedLikeResponse)
	err := c.cc.Invoke(ctx, WorkoutService_ToggleFeedLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) AddFeedComment(ctx context.Context, in *AddFeedCommentRequest, opts ...grpc.CallOption) (*FeedComment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedComment)
	err := c.cc.Invoke(ctx, WorkoutService_AddFeedComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) ListFeedComments(ctx context.Context, in *ListFeedCommentsRequest, opts ...grpc.CallOption) (*ListFeedCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedCommentsResponse)
	err := c.cc.Invoke(ctx, WorkoutService_ListFeedComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workoutServiceClient) StreamWorkout(ctx context.Context, in *StreamWorkoutRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkoutUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkoutService_ServiceDesc.Streams[0], WorkoutService_StreamWorkout_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamWorkoutRequest, WorkoutUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkoutService_StreamWorkoutClient = grpc.ServerStreamingClient[WorkoutUpdate]

// WorkoutServiceServer is the server API for WorkoutService service.
// All implementations must embed UnimplementedWorkoutServiceServer
// for forward compatibility.
type WorkoutServiceServer interface {
	CreateWorkout(context.Context, *CreateWorkoutRequest) (*CreateWorkoutResponse, error)
	GetWorkout(context.Context, *GetWorkoutRequest) (*GetWorkoutResponse, error)
	ListWorkouts(context.Context, *ListWorkoutsRequest) (*ListWorkoutsResponse, error)
	ListFeedPosts(context.Context, *ListFeedPostsRequest) (*ListFeedPostsResponse, error)
	GetFeedPost(context.Context, *GetFeedPostRequest) (*FeedPost, error)
	ToggleFeedLike(context.Context, *ToggleFeedLikeRequest) (*ToggleFeedLikeResponse, error)
	AddFeedComment(context.Context, *AddFeedCommentRequest) (*FeedComment, error)
	ListFeedComments(context.Context, *ListFeedCommentsRequest) (*ListFeedCommentsResponse, error)
	StreamWorkout(*StreamWorkoutRequest, grpc.ServerStreamingServer[WorkoutUpdate]) error
	mustEmbedUnimplementedWorkoutServiceServer()
}

// UnimplementedWorkoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkoutServiceServer struct{}

func (UnimplementedWorkoutServiceServer) CreateWorkout(context.Context, *CreateWorkoutRequest) (*CreateWorkoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) GetWorkout(context.Context, *GetWorkoutRequest) (*GetWorkoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) ListWorkouts(context.Context, *ListWorkoutsRequest) (*ListWorkoutsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkouts not implemented")
}
func (UnimplementedWorkoutServiceServer) ListFeedPosts(context.Context, *ListFeedPostsRequest) (*ListFeedPostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeedPosts not implemented")
}
func (UnimplementedWorkoutServiceServer) GetFeedPost(context.Context, *GetFeedPostRequest) (*FeedPost, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedPost not implemented")
}
func (UnimplementedWorkoutServiceServer) ToggleFeedLike(context.Context, *ToggleFeedLikeRequest) (*ToggleFeedLikeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleFeedLike not implemented")
}
func (UnimplementedWorkoutServiceServer) AddFeedComment(context.Context, *AddFeedCommentRequest) (*FeedComment, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFeedComment not implemented")
}
func (UnimplementedWorkoutServiceServer) ListFeedComments(context.Context, *ListFeedCommentsRequest) (*ListFeedCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeedComments not implemented")
}
func (UnimplementedWorkoutServiceServer) StreamWorkout(*StreamWorkoutRequest, grpc.ServerStreamingServer[WorkoutUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamWorkout not implemented")
}
func (UnimplementedWorkoutServiceServer) mustEmbedUnimplementedWorkoutServiceServer() {}
func (UnimplementedWorkoutServiceServer) testEmbeddedByValue()                        {}

// UnsafeWorkoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkoutServiceServer will
// result in compilation errors.
type UnsafeWorkoutServiceServer interface {
	mustEmbedUnimplementedWorkoutServiceServer()
}

func RegisterWorkoutServiceServer(s grpc.ServiceRegistrar, srv WorkoutServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkoutService_ServiceDesc, srv)
}

func _WorkoutService_CreateWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).CreateWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_CreateWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).CreateWorkout(ctx, req.(*CreateWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetWorkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetWorkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetWorkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetWorkout(ctx, req.(*GetWorkoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_ListWorkouts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkoutsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).ListWorkouts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_ListWorkouts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).ListWorkouts(ctx, req.(*ListWorkoutsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_ListFeedPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).ListFeedPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_ListFeedPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).ListFeedPosts(ctx, req.(*ListFeedPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_GetFeedPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).GetFeedPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_GetFeedPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).GetFeedPost(ctx, req.(*GetFeedPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_ToggleFeedLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleFeedLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).ToggleFeedLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_ToggleFeedLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).ToggleFeedLike(ctx, req.(*ToggleFeedLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_AddFeedComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFeedCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).AddFeedComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_AddFeedComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).AddFeedComment(ctx, req.(*AddFeedCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_ListFeedComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkoutServiceServer).ListFeedComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkoutService_ListFeedComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkoutServiceServer).ListFeedComments(ctx, req.(*ListFeedCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkoutService_StreamWorkout_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamWorkoutRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkoutServiceServer).StreamWorkout(m, &grpc.GenericServerStream[StreamWorkoutRequest, WorkoutUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkoutService_StreamWorkoutServer = grpc.ServerStreamingServer[WorkoutUpdate]

// WorkoutService_ServiceDesc is the grpc.ServiceDesc for WorkoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zenx.workout.v1.WorkoutService",
	HandlerType: (*WorkoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkout",
			Handler:    _WorkoutService_CreateWorkout_Handler,
		},
		{
			MethodName: "GetWorkout",
			Handler:    _WorkoutService_GetWorkout_Handler,
		},
		{
			MethodName: "ListWorkouts",
			Handler:    _WorkoutService_ListWorkouts_Handler,
		},
		{
			MethodName: "ListFeedPosts",
			Handler:    _WorkoutService_ListFeedPosts_Handler,
		},
		{
			MethodName: "GetFeedPost",
			Handler:    _WorkoutService_GetFeedPost_Handler,
		},
		{
			MethodName: "ToggleFeedLike",
			Handler:    _WorkoutService_ToggleFeedLike_Handler,
		},
		{
			MethodName: "AddFeedComment",
			Handler:    _WorkoutService_AddFeedComment_Handler,
		},
		{
			MethodName: "ListFeedComments",
			Handler:    _WorkoutService_ListFeedComments_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWorkout",
			Handler:       _WorkoutService_StreamWorkout_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workout/v1/workout.proto",
}
