// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workout/v1/workout.proto

package workoutv1

import (
	v1 "github.com/zenx/backend/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteFeedCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeedCommentRequest) Reset() {
	*x = DeleteFeedCommentRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeedCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeedCommentRequest) ProtoMessage() {}

func (x *DeleteFeedCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeedCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteFeedCommentRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteFeedCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *DeleteFeedCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WorkoutExercise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    string                 `protobuf:"bytes,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	Order         int32                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Sets          []*WorkoutSet          `protobuf:"bytes,3,rep,name=sets,proto3" json:"sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutExercise) Reset() {
	*x = WorkoutExercise{}
	mi := &file_workout_v1_workout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutExercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutExercise) ProtoMessage() {}

func (x *WorkoutExercise) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutExercise.ProtoReflect.Descriptor instead.
func (*WorkoutExercise) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{1}
}

func (x *WorkoutExercise) GetExerciseId() string {
	if x != nil {
		return x.ExerciseId
	}
	return ""
}

func (x *WorkoutExercise) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *WorkoutExercise) GetSets() []*WorkoutSet {
	if x != nil {
		return x.Sets
	}
	return nil
}

type WorkoutSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetNumber     int32                  `protobuf:"varint,1,opt,name=set_number,json=setNumber,proto3" json:"set_number,omitempty"`
	Reps          int32                  `protobuf:"varint,2,opt,name=reps,proto3" json:"reps,omitempty"`
	WeightKg      float64                `protobuf:"fixed64,3,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	Rpe           float64                `protobuf:"fixed64,4,opt,name=rpe,proto3" json:"rpe,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	Completed     bool                   `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutSet) Reset() {
	*x = WorkoutSet{}
	mi := &file_workout_v1_workout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutSet) ProtoMessage() {}

func (x *WorkoutSet) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutSet.ProtoReflect.Descriptor instead.
func (*WorkoutSet) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{2}
}

func (x *WorkoutSet) GetSetNumber() int32 {
	if x != nil {
		return x.SetNumber
	}
	return 0
}

func (x *WorkoutSet) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *WorkoutSet) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *WorkoutSet) GetRpe() float64 {
	if x != nil {
		return x.Rpe
	}
	return 0
}

func (x *WorkoutSet) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *WorkoutSet) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type CreateWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	Exercises     []*WorkoutExercise     `protobuf:"bytes,4,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkoutRequest) Reset() {
	*x = CreateWorkoutRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkoutRequest) ProtoMessage() {}

func (x *CreateWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkoutRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWorkoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateWorkoutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkoutRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreateWorkoutRequest) GetExercises() []*WorkoutExercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

type CreateWorkoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutId     string                 `protobuf:"bytes,1,opt,name=workout_id,json=workoutId,proto3" json:"workout_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkoutResponse) Reset() {
	*x = CreateWorkoutResponse{}
	mi := &file_workout_v1_workout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkoutResponse) ProtoMessage() {}

func (x *CreateWorkoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkoutResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkoutResponse) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkoutResponse) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

func (x *CreateWorkoutResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type UpdateWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutId     string                 `protobuf:"bytes,1,opt,name=workout_id,json=workoutId,proto3" json:"workout_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	Exercises     []*WorkoutExercise     `protobuf:"bytes,5,rep,name=exercises,proto3" json:"exercises,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkoutRequest) Reset() {
	*x = UpdateWorkoutRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkoutRequest) ProtoMessage() {}

func (x *UpdateWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkoutRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWorkoutRequest) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

func (x *UpdateWorkoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateWorkoutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWorkoutRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdateWorkoutRequest) GetExercises() []*WorkoutExercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

func (x *UpdateWorkoutRequest) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *UpdateWorkoutRequest) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type DeleteWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutId     string                 `protobuf:"bytes,1,opt,name=workout_id,json=workoutId,proto3" json:"workout_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkoutRequest) Reset() {
	*x = DeleteWorkoutRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkoutRequest) ProtoMessage() {}

func (x *DeleteWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkoutRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteWorkoutRequest) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

func (x *DeleteWorkoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutId     string                 `protobuf:"bytes,1,opt,name=workout_id,json=workoutId,proto3" json:"workout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkoutRequest) Reset() {
	*x = GetWorkoutRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkoutRequest) ProtoMessage() {}

func (x *GetWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkoutRequest.ProtoReflect.Descriptor instead.
func (*GetWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{7}
}

func (x *GetWorkoutRequest) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

type GetWorkoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workout       *Workout               `protobuf:"bytes,1,opt,name=workout,proto3" json:"workout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkoutResponse) Reset() {
	*x = GetWorkoutResponse{}
	mi := &file_workout_v1_workout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkoutResponse) ProtoMessage() {}

func (x *GetWorkoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkoutResponse.ProtoReflect.Descriptor instead.
func (*GetWorkoutResponse) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkoutResponse) GetWorkout() *Workout {
	if x != nil {
		return x.Workout
	}
	return nil
}

type ListWorkoutsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkoutsRequest) Reset() {
	*x = ListWorkoutsRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkoutsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkoutsRequest) ProtoMessage() {}

func (x *ListWorkoutsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkoutsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkoutsRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{9}
}

func (x *ListWorkoutsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListWorkoutsRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListWorkoutsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workouts      []*Workout             `protobuf:"bytes,1,rep,name=workouts,proto3" json:"workouts,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkoutsResponse) Reset() {
	*x = ListWorkoutsResponse{}
	mi := &file_workout_v1_workout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkoutsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkoutsResponse) ProtoMessage() {}

func (x *ListWorkoutsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkoutsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkoutsResponse) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{10}
}

func (x *ListWorkoutsResponse) GetWorkouts() []*Workout {
	if x != nil {
		return x.Workouts
	}
	return nil
}

func (x *ListWorkoutsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type ListFeedPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Discover      bool                   `protobuf:"varint,3,opt,name=discover,proto3" json:"discover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedPostsRequest) Reset() {
	*x = ListFeedPostsRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedPostsRequest) ProtoMessage() {}

func (x *ListFeedPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedPostsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedPostsRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{11}
}

func (x *ListFeedPostsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFeedPostsRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListFeedPostsRequest) GetDiscover() bool {
	if x != nil {
		return x.Discover
	}
	return false
}

type ListFeedPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*FeedPost            `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedPostsResponse) Reset() {
	*x = ListFeedPostsResponse{}
	mi := &file_workout_v1_workout_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedPostsResponse) ProtoMessage() {}

func (x *ListFeedPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedPostsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedPostsResponse) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{12}
}

func (x *ListFeedPostsResponse) GetPosts() []*FeedPost {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListFeedPostsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetFeedPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedPostRequest) Reset() {
	*x = GetFeedPostRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedPostRequest) ProtoMessage() {}

func (x *GetFeedPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedPostRequest.ProtoReflect.Descriptor instead.
func (*GetFeedPostRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{13}
}

func (x *GetFeedPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetFeedPostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FeedPost struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkoutId      string                 `protobuf:"bytes,2,opt,name=workout_id,json=workoutId,proto3" json:"workout_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption        string                 `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	ImageUrl       string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LikesCount     int32                  `protobuf:"varint,8,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	CommentsCount  int32                  `protobuf:"varint,9,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	LikedByViewer  bool                   `protobuf:"varint,10,opt,name=liked_by_viewer,json=likedByViewer,proto3" json:"liked_by_viewer,omitempty"`
	SampleLikerIds []string               `protobuf:"bytes,11,rep,name=sample_liker_ids,json=sampleLikerIds,proto3" json:"sample_liker_ids,omitempty"`
	Workout        *Workout               `protobuf:"bytes,12,opt,name=workout,proto3" json:"workout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FeedPost) Reset() {
	*x = FeedPost{}
	mi := &file_workout_v1_workout_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedPost) ProtoMessage() {}

func (x *FeedPost) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedPost.ProtoReflect.Descriptor instead.
func (*FeedPost) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{14}
}

func (x *FeedPost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedPost) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

func (x *FeedPost) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FeedPost) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *FeedPost) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *FeedPost) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FeedPost) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *FeedPost) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *FeedPost) GetCommentsCount() int32 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *FeedPost) GetLikedByViewer() bool {
	if x != nil {
		return x.LikedByViewer
	}
	return false
}

func (x *FeedPost) GetSampleLikerIds() []string {
	if x != nil {
		return x.SampleLikerIds
	}
	return nil
}

func (x *FeedPost) GetWorkout() *Workout {
	if x != nil {
		return x.Workout
	}
	return nil
}

type ToggleFeedLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFeedLikeRequest) Reset() {
	*x = ToggleFeedLikeRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFeedLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFeedLikeRequest) ProtoMessage() {}

func (x *ToggleFeedLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFeedLikeRequest.ProtoReflect.Descriptor instead.
func (*ToggleFeedLikeRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{15}
}

func (x *ToggleFeedLikeRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *ToggleFeedLikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ToggleFeedLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	LikesCount    int32                  `protobuf:"varint,2,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFeedLikeResponse) Reset() {
	*x = ToggleFeedLikeResponse{}
	mi := &file_workout_v1_workout_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFeedLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFeedLikeResponse) ProtoMessage() {}

func (x *ToggleFeedLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFeedLikeResponse.ProtoReflect.Descriptor instead.
func (*ToggleFeedLikeResponse) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{16}
}

func (x *ToggleFeedLikeResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *ToggleFeedLikeResponse) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

type AddFeedCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeedCommentRequest) Reset() {
	*x = AddFeedCommentRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeedCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedCommentRequest) ProtoMessage() {}

func (x *AddFeedCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedCommentRequest.ProtoReflect.Descriptor instead.
func (*AddFeedCommentRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{17}
}

func (x *AddFeedCommentRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *AddFeedCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddFeedCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type FeedComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedComment) Reset() {
	*x = FeedComment{}
	mi := &file_workout_v1_workout_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedComment) ProtoMessage() {}

func (x *FeedComment) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedComment.ProtoReflect.Descriptor instead.
func (*FeedComment) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{18}
}

func (x *FeedComment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedComment) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *FeedComment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FeedComment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *FeedComment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListFeedCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Pagination    *v1.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedCommentsRequest) Reset() {
	*x = ListFeedCommentsRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedCommentsRequest) ProtoMessage() {}

func (x *ListFeedCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedCommentsRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{19}
}

func (x *ListFeedCommentsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *ListFeedCommentsRequest) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListFeedCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*FeedComment         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedCommentsResponse) Reset() {
	*x = ListFeedCommentsResponse{}
	mi := &file_workout_v1_workout_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedCommentsResponse) ProtoMessage() {}

func (x *ListFeedCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedCommentsResponse) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{20}
}

func (x *ListFeedCommentsResponse) GetComments() []*FeedComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListFeedCommentsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type StreamWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutId     string                 `protobuf:"bytes,1,opt,name=workout_id,json=workoutId,proto3" json:"workout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamWorkoutRequest) Reset() {
	*x = StreamWorkoutRequest{}
	mi := &file_workout_v1_workout_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWorkoutRequest) ProtoMessage() {}

func (x *StreamWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWorkoutRequest.ProtoReflect.Descriptor instead.
func (*StreamWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{21}
}

func (x *StreamWorkoutRequest) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

type WorkoutUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkoutId     string                 `protobuf:"bytes,1,opt,name=workout_id,json=workoutId,proto3" json:"workout_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	OccurredAt    int64                  `protobuf:"varint,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkoutUpdate) Reset() {
	*x = WorkoutUpdate{}
	mi := &file_workout_v1_workout_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkoutUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkoutUpdate) ProtoMessage() {}

func (x *WorkoutUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkoutUpdate.ProtoReflect.Descriptor instead.
func (*WorkoutUpdate) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{22}
}

func (x *WorkoutUpdate) GetWorkoutId() string {
	if x != nil {
		return x.WorkoutId
	}
	return ""
}

func (x *WorkoutUpdate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkoutUpdate) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *WorkoutUpdate) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

type Workout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	StartedAt     int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Exercises     []*WorkoutExercise     `protobuf:"bytes,7,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workout) Reset() {
	*x = Workout{}
	mi := &file_workout_v1_workout_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workout) ProtoMessage() {}

func (x *Workout) ProtoReflect() protoreflect.Message {
	mi := &file_workout_v1_workout_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workout.ProtoReflect.Descriptor instead.
func (*Workout) Descriptor() ([]byte, []int) {
	return file_workout_v1_workout_proto_rawDescGZIP(), []int{23}
}

func (x *Workout) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workout) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Workout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workout) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Workout) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Workout) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Workout) GetExercises() []*WorkoutExercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

var File_workout_v1_workout_proto protoreflect.FileDescriptor

const file_workout_v1_workout_proto_rawDesc = "" +
	"\n" +
	"\x18workout/v1/workout.proto\x12\x0fzenx.workout.v1\x1a\x16common/v1/common.proto\"R\n" +
	"\x18DeleteFeedCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"y\n" +
	"\x0fWorkoutExercise\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\tR\n" +
	"exerciseId\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x05R\x05order\x12/\n" +
	"\x04sets\x18\x03 \x03(\v2\x1b.zenx.workout.v1.WorkoutSetR\x04sets\"\xa2\x01\n" +
	"\n" +
	"WorkoutSet\x12\x1d\n" +
	"\n" +
	"set_number\x18\x01 \x01(\x05R\tsetNumber\x12\x12\n" +
	"\x04reps\x18\x02 \x01(\x05R\x04reps\x12\x1b\n" +
	"\tweight_kg\x18\x03 \x01(\x01R\bweightKg\x12\x10\n" +
	"\x03rpe\x18\x04 \x01(\x01R\x03rpe\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\x12\x1c\n" +
	"\tcompleted\x18\x06 \x01(\bR\tcompleted\"\x99\x01\n" +
	"\x14CreateWorkoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12>\n" +
	"\texercises\x18\x04 \x03(\v2 .zenx.workout.v1.WorkoutExerciseR\texercises\"U\n" +
	"\x15CreateWorkoutResponse\x12\x1d\n" +
	"\n" +
	"workout_id\x18\x01 \x01(\tR\tworkoutId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\"\xfa\x01\n" +
	"\x14UpdateWorkoutRequest\x12\x1d\n" +
	"\n" +
	"workout_id\x18\x01 \x01(\tR\tworkoutId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\x12>\n" +
	"\texercises\x18\x05 \x03(\v2 .zenx.workout.v1.WorkoutExerciseR\texercises\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\a \x01(\x03R\vcompletedAt\"N\n" +
	"\x14DeleteWorkoutRequest\x12\x1d\n" +
	"\n" +
	"workout_id\x18\x01 \x01(\tR\tworkoutId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"2\n" +
	"\x11GetWorkoutRequest\x12\x1d\n" +
	"\n" +
	"workout_id\x18\x01 \x01(\tR\tworkoutId\"H\n" +
	"\x12GetWorkoutResponse\x122\n" +
	"\aworkout\x18\x01 \x01(\v2\x18.zenx.workout.v1.WorkoutR\aworkout\"j\n" +
	"\x13ListWorkoutsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.zenx.common.v1.PaginationR\n" +
	"pagination\"m\n" +
	"\x14ListWorkoutsResponse\x124\n" +
	"\bworkouts\x18\x01 \x03(\v2\x18.zenx.workout.v1.WorkoutR\bworkouts\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x87\x01\n" +
	"\x14ListFeedPostsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.zenx.common.v1.PaginationR\n" +
	"pagination\x12\x1a\n" +
	"\bdiscover\x18\x03 \x01(\bR\bdiscover\"i\n" +
	"\x15ListFeedPostsResponse\x12/\n" +
	"\x05posts\x18\x01 \x03(\v2\x19.zenx.workout.v1.FeedPostR\x05posts\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"F\n" +
	"\x12GetFeedPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x95\x03\n" +
	"\bFeedPost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"workout_id\x18\x02 \x01(\tR\tworkoutId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\acaption\x18\x04 \x01(\tR\acaption\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x1f\n" +
	"\vlikes_count\x18\b \x01(\x05R\n" +
	"likesCount\x12%\n" +
	"\x0ecomments_count\x18\t \x01(\x05R\rcommentsCount\x12&\n" +
	"\x0fliked_by_viewer\x18\n" +
	" \x01(\bR\rlikedByViewer\x12(\n" +
	"\x10sample_liker_ids\x18\v \x03(\tR\x0esampleLikerIds\x122\n" +
	"\aworkout\x18\f \x01(\v2\x18.zenx.workout.v1.WorkoutR\aworkout\"I\n" +
	"\x15ToggleFeedLikeRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"O\n" +
	"\x16ToggleFeedLikeResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x1f\n" +
	"\vlikes_count\x18\x02 \x01(\x05R\n" +
	"likesCount\"]\n" +
	"\x15AddFeedCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"\x82\x01\n" +
	"\vFeedComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"n\n" +
	"\x17ListFeedCommentsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.zenx.common.v1.PaginationR\n" +
	"pagination\"u\n" +
	"\x18ListFeedCommentsResponse\x128\n" +
	"\bcomments\x18\x01 \x03(\v2\x1c.zenx.workout.v1.FeedCommentR\bcomments\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"5\n" +
	"\x14StreamWorkoutRequest\x12\x1d\n" +
	"\n" +
	"workout_id\x18\x01 \x01(\tR\tworkoutId\"}\n" +
	"\rWorkoutUpdate\x12\x1d\n" +
	"\n" +
	"workout_id\x18\x01 \x01(\tR\tworkoutId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\x03R\n" +
	"occurredAt\"\xde\x01\n" +
	"\aWorkout\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x06 \x01(\x03R\vcompletedAt\x12>\n" +
	"\texercises\x18\a \x03(\v2 .zenx.workout.v1.WorkoutExerciseR\texercises2\xc9\b\n" +
	"\x0eWorkoutService\x12^\n" +
	"\rCreateWorkout\x12%.zenx.workout.v1.CreateWorkoutRequest\x1a&.zenx.workout.v1.CreateWorkoutResponse\x12P\n" +
	"\rUpdateWorkout\x12%.zenx.workout.v1.UpdateWorkoutRequest\x1a\x18.zenx.workout.v1.Workout\x12M\n" +
	"\rDeleteWorkout\x12%.zenx.workout.v1.DeleteWorkoutRequest\x1a\x15.zenx.common.v1.Empty\x12U\n" +
	"\n" +
	"GetWorkout\x12\".zenx.workout.v1.GetWorkoutRequest\x1a#.zenx.workout.v1.GetWorkoutResponse\x12[\n" +
	"\fListWorkouts\x12$.zenx.workout.v1.ListWorkoutsRequest\x1a%.zenx.workout.v1.ListWorkoutsResponse\x12^\n" +
	"\rListFeedPosts\x12%.zenx.workout.v1.ListFeedPostsRequest\x1a&.zenx.workout.v1.ListFeedPostsResponse\x12M\n" +
	"\vGetFeedPost\x12#.zenx.workout.v1.GetFeedPostRequest\x1a\x19.zenx.workout.v1.FeedPost\x12a\n" +
	"\x0eToggleFeedLike\x12&.zenx.workout.v1.ToggleFeedLikeRequest\x1a'.zenx.workout.v1.ToggleFeedLikeResponse\x12V\n" +
	"\x0eAddFeedComment\x12&.zenx.workout.v1.AddFeedCommentRequest\x1a\x1c.zenx.workout.v1.FeedComment\x12g\n" +
	"\x10ListFeedComments\x12(.zenx.workout.v1.ListFeedCommentsRequest\x1a).zenx.workout.v1.ListFeedCommentsResponse\x12U\n" +
	"\x11DeleteFeedComment\x12).zenx.workout.v1.DeleteFeedCommentRequest\x1a\x15.zenx.common.v1.Empty\x12X\n" +
	"\rStreamWorkout\x12%.zenx.workout.v1.StreamWorkoutRequest\x1a\x1e.zenx.workout.v1.WorkoutUpdate0\x01B4Z2github.com/zenx/backend/proto/workout/v1;workoutv1b\x06proto3"

var (
	file_workout_v1_workout_proto_rawDescOnce sync.Once
	file_workout_v1_workout_proto_rawDescData []byte
)

func file_workout_v1_workout_proto_rawDescGZIP() []byte {
	file_workout_v1_workout_proto_rawDescOnce.Do(func() {
		file_workout_v1_workout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workout_v1_workout_proto_rawDesc), len(file_workout_v1_workout_proto_rawDesc)))
	})
	return file_workout_v1_workout_proto_rawDescData
}

var file_workout_v1_workout_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_workout_v1_workout_proto_goTypes = []any{
	(*DeleteFeedCommentRequest)(nil), // 0: zenx.workout.v1.DeleteFeedCommentRequest
	(*WorkoutExercise)(nil),          // 1: zenx.workout.v1.WorkoutExercise
	(*WorkoutSet)(nil),               // 2: zenx.workout.v1.WorkoutSet
	(*CreateWorkoutRequest)(nil),     // 3: zenx.workout.v1.CreateWorkoutRequest
	(*CreateWorkoutResponse)(nil),    // 4: zenx.workout.v1.CreateWorkoutResponse
	(*UpdateWorkoutRequest)(nil),     // 5: zenx.workout.v1.UpdateWorkoutRequest
	(*DeleteWorkoutRequest)(nil),     // 6: zenx.workout.v1.DeleteWorkoutRequest
	(*GetWorkoutRequest)(nil),        // 7: zenx.workout.v1.GetWorkoutRequest
	(*GetWorkoutResponse)(nil),       // 8: zenx.workout.v1.GetWorkoutResponse
	(*ListWorkoutsRequest)(nil),      // 9: zenx.workout.v1.ListWorkoutsRequest
	(*ListWorkoutsResponse)(nil),     // 10: zenx.workout.v1.ListWorkoutsResponse
	(*ListFeedPostsRequest)(nil),     // 11: zenx.workout.v1.ListFeedPostsRequest
	(*ListFeedPostsResponse)(nil),    // 12: zenx.workout.v1.ListFeedPostsResponse
	(*GetFeedPostRequest)(nil),       // 13: zenx.workout.v1.GetFeedPostRequest
	(*FeedPost)(nil),                 // 14: zenx.workout.v1.FeedPost
	(*ToggleFeedLikeRequest)(nil),    // 15: zenx.workout.v1.ToggleFeedLikeRequest
	(*ToggleFeedLikeResponse)(nil),   // 16: zenx.workout.v1.ToggleFeedLikeResponse
	(*AddFeedCommentRequest)(nil),    // 17: zenx.workout.v1.AddFeedCommentRequest
	(*FeedComment)(nil),              // 18: zenx.workout.v1.FeedComment
	(*ListFeedCommentsRequest)(nil),  // 19: zenx.workout.v1.ListFeedCommentsRequest
	(*ListFeedCommentsResponse)(nil), // 20: zenx.workout.v1.ListFeedCommentsResponse
	(*StreamWorkoutRequest)(nil),     // 21: zenx.workout.v1.StreamWorkoutRequest
	(*WorkoutUpdate)(nil),            // 22: zenx.workout.v1.WorkoutUpdate
	(*Workout)(nil),                  // 23: zenx.workout.v1.Workout
	(*v1.Pagination)(nil),            // 24: zenx.common.v1.Pagination
	(*v1.Empty)(nil),                 // 25: zenx.common.v1.Empty
}
var file_workout_v1_workout_proto_depIdxs = []int32{
	2,  // 0: zenx.workout.v1.WorkoutExercise.sets:type_name -> zenx.workout.v1.WorkoutSet
	1,  // 1: zenx.workout.v1.CreateWorkoutRequest.exercises:type_name -> zenx.workout.v1.WorkoutExercise
	1,  // 2: zenx.workout.v1.UpdateWorkoutRequest.exercises:type_name -> zenx.workout.v1.WorkoutExercise
	23, // 3: zenx.workout.v1.GetWorkoutResponse.workout:type_name -> zenx.workout.v1.Workout
	24, // 4: zenx.workout.v1.ListWorkoutsRequest.pagination:type_name -> zenx.common.v1.Pagination
	23, // 5: zenx.workout.v1.ListWorkoutsResponse.workouts:type_name -> zenx.workout.v1.Workout
	24, // 6: zenx.workout.v1.ListFeedPostsRequest.pagination:type_name -> zenx.common.v1.Pagination
	14, // 7: zenx.workout.v1.ListFeedPostsResponse.posts:type_name -> zenx.workout.v1.FeedPost
	23, // 8: zenx.workout.v1.FeedPost.workout:type_name -> zenx.workout.v1.Workout
	24, // 9: zenx.workout.v1.ListFeedCommentsRequest.pagination:type_name -> zenx.common.v1.Pagination
	18, // 10: zenx.workout.v1.ListFeedCommentsResponse.comments:type_name -> zenx.workout.v1.FeedComment
	1,  // 11: zenx.workout.v1.Workout.exercises:type_name -> zenx.workout.v1.WorkoutExercise
	3,  // 12: zenx.workout.v1.WorkoutService.CreateWorkout:input_type -> zenx.workout.v1.CreateWorkoutRequest
	5,  // 13: zenx.workout.v1.WorkoutService.UpdateWorkout:input_type -> zenx.workout.v1.UpdateWorkoutRequest
	6,  // 14: zenx.workout.v1.WorkoutService.DeleteWorkout:input_type -> zenx.workout.v1.DeleteWorkoutRequest
	7,  // 15: zenx.workout.v1.WorkoutService.GetWorkout:input_type -> zenx.workout.v1.GetWorkoutRequest
	9,  // 16: zenx.workout.v1.WorkoutService.ListWorkouts:input_type -> zenx.workout.v1.ListWorkoutsRequest
	11, // 17: zenx.workout.v1.WorkoutService.ListFeedPosts:input_type -> zenx.workout.v1.ListFeedPostsRequest
	13, // 18: zenx.workout.v1.WorkoutService.GetFeedPost:input_type -> zenx.workout.v1.GetFeedPostRequest
	15, // 19: zenx.workout.v1.WorkoutService.ToggleFeedLike:input_type -> zenx.workout.v1.ToggleFeedLikeRequest
	17, // 20: zenx.workout.v1.WorkoutService.AddFeedComment:input_type -> zenx.workout.v1.AddFeedCommentRequest
	19, // 21: zenx.workout.v1.WorkoutService.ListFeedComments:input_type -> zenx.workout.v1.ListFeedCommentsRequest
	0,  // 22: zenx.workout.v1.WorkoutService.DeleteFeedComment:input_type -> zenx.workout.v1.DeleteFeedCommentRequest
	21, // 23: zenx.workout.v1.WorkoutService.StreamWorkout:input_type -> zenx.workout.v1.StreamWorkoutRequest
	4,  // 24: zenx.workout.v1.WorkoutService.CreateWorkout:output_type -> zenx.workout.v1.CreateWorkoutResponse
	23, // 25: zenx.workout.v1.WorkoutService.UpdateWorkout:output_type -> zenx.workout.v1.Workout
	25, // 26: zenx.workout.v1.WorkoutService.DeleteWorkout:output_type -> zenx.common.v1.Empty
	8,  // 27: zenx.workout.v1.WorkoutService.GetWorkout:output_type -> zenx.workout.v1.GetWorkoutResponse
	10, // 28: zenx.workout.v1.WorkoutService.ListWorkouts:output_type -> zenx.workout.v1.ListWorkoutsResponse
	12, // 29: zenx.workout.v1.WorkoutService.ListFeedPosts:output_type -> zenx.workout.v1.ListFeedPostsResponse
	14, // 30: zenx.workout.v1.WorkoutService.GetFeedPost:output_type -> zenx.workout.v1.FeedPost
	16, // 31: zenx.workout.v1.WorkoutService.ToggleFeedLike:output_type -> zenx.workout.v1.ToggleFeedLikeResponse
	18, // 32: zenx.workout.v1.WorkoutService.AddFeedComment:output_type -> zenx.workout.v1.FeedComment
	20, // 33: zenx.workout.v1.WorkoutService.ListFeedComments:output_type -> zenx.workout.v1.ListFeedCommentsResponse
	25, // 34: zenx.workout.v1.WorkoutService.DeleteFeedComment:output_type -> zenx.common.v1.Empty
	22, // 35: zenx.workout.v1.WorkoutService.StreamWorkout:output_type -> zenx.workout.v1.WorkoutUpdate
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_workout_v1_workout_proto_init() }
func file_workout_v1_workout_proto_init() {
	if File_workout_v1_workout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workout_v1_workout_proto_rawDesc), len(file_workout_v1_workout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workout_v1_workout_proto_goTypes,
		DependencyIndexes: file_workout_v1_workout_proto_depIdxs,
		MessageInfos:      file_workout_v1_workout_proto_msgTypes,
	}.Build()
	File_workout_v1_workout_proto = out.File
	file_workout_v1_workout_proto_goTypes = nil
	file_workout_v1_workout_proto_depIdxs = nil
}
