package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/zenx/backend/cmd/gateway/graph/model"
	analyticsv1 "github.com/zenx/backend/proto/analytics/v1"
	authv1 "github.com/zenx/backend/proto/auth/v1"
	commonv1 "github.com/zenx/backend/proto/common/v1"
	exercisev1 "github.com/zenx/backend/proto/exercise/v1"
	notificationv1 "github.com/zenx/backend/proto/notification/v1"
	profilev1 "github.com/zenx/backend/proto/profile/v1"
	workoutv1 "github.com/zenx/backend/proto/workout/v1"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string, displayName string) (*model.AuthPayload, error) {
	_, err := r.AuthClient.RegisterUser(ctx, &authv1.RegisterUserRequest{
		Email:       email,
		Password:    password,
		DisplayName: displayName,
	})
	if err != nil {
		return nil, err
	}
	// After registration, automatically log in the user
	resp, err := r.AuthClient.Login(ctx, &authv1.LoginRequest{Email: email, Password: password})
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
		ExpiresAt:    time.Unix(resp.GetExpiresAt(), 0).UTC().Format(time.RFC3339),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	resp, err := r.AuthClient.Login(ctx, &authv1.LoginRequest{Email: email, Password: password})
	if err != nil {
		return nil, err
	}
	return &model.AuthPayload{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
		ExpiresAt:    time.Unix(resp.GetExpiresAt(), 0).UTC().Format(time.RFC3339),
	}, nil
}

// CreateWorkout is the resolver for the createWorkout field.
func (r *mutationResolver) CreateWorkout(ctx context.Context, input model.WorkoutInput) (*model.Workout, error) {
	userID := input.UserID
	if userID == "" {
		if uc, ok := GetUserContext(ctx); ok {
			userID = uc.UserID
		}
	}
	if userID == "" {
		return nil, fmt.Errorf("userId is required")
	}

	req := &workoutv1.CreateWorkoutRequest{
		UserId: userID,
		Name:   input.Name,
		Notes:  getStringValue(input.Notes),
	}

	// Convert exercises from GraphQL input to proto
	if input.Exercises != nil {
		for _, exInput := range input.Exercises {
			exProto := &workoutv1.WorkoutExercise{
				ExerciseId: exInput.ExerciseID,
				Order:      int32(exInput.Order),
			}
			for _, setInput := range exInput.Sets {
				exProto.Sets = append(exProto.Sets, &workoutv1.WorkoutSet{
					SetNumber: int32(setInput.SetNumber),
					Reps:      int32(getIntValue(setInput.Reps)),
					WeightKg:  getFloatValue(setInput.WeightKg),
					Rpe:       getFloatValue(setInput.Rpe),
					Notes:     getStringValue(setInput.Notes),
					Completed: getBoolValue(setInput.Completed),
				})
			}
			req.Exercises = append(req.Exercises, exProto)
		}
	}

	resp, err := r.WorkoutClient.CreateWorkout(ctx, req)
	if err != nil {
		return nil, err
	}

	workoutResp, err := r.WorkoutClient.GetWorkout(ctx, &workoutv1.GetWorkoutRequest{WorkoutId: resp.GetWorkoutId()})
	if err != nil {
		return nil, err
	}

	return convertWorkout(workoutResp.GetWorkout()), nil
}

// UpdateWorkout is the resolver for the updateWorkout field.
func (r *mutationResolver) UpdateWorkout(ctx context.Context, id string, input model.UpdateWorkoutInput) (*model.Workout, error) {
	panic(fmt.Errorf("not implemented: UpdateWorkout - updateWorkout"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	resp, err := r.AuthClient.RefreshToken(ctx, &authv1.RefreshTokenRequest{RefreshToken: refreshToken})
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		AccessToken:  resp.GetAccessToken(),
		RefreshToken: resp.GetRefreshToken(),
		ExpiresAt:    time.Unix(resp.GetExpiresAt(), 0).UTC().Format(time.RFC3339),
	}, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.ProfileInput) (*model.Profile, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	payload := &profilev1.Profile{UserId: uc.UserID}
	if input.DisplayName != nil {
		payload.DisplayName = getStringValue(input.DisplayName)
	}
	if input.Bio != nil {
		payload.Bio = getStringValue(input.Bio)
	}
	if input.AvatarURL != nil {
		payload.AvatarUrl = getStringValue(input.AvatarURL)
	}
	if input.DateOfBirth != nil {
		payload.DateOfBirth = getStringValue(input.DateOfBirth)
	}
	if input.Gender != nil {
		payload.Gender = getStringValue(input.Gender)
	}

	resp, err := r.ProfileClient.UpdateProfile(ctx, &profilev1.UpdateProfileRequest{Profile: payload})
	if err != nil {
		return nil, err
	}
	return convertProfile(resp), nil
}

// RecordMeasurement is the resolver for the recordMeasurement field.
func (r *mutationResolver) RecordMeasurement(ctx context.Context, input model.MeasurementInput) (*model.Measurement, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	if input.MeasurementDate == "" {
		return nil, fmt.Errorf("measurementDate is required")
	}
	if _, err := time.Parse("2006-01-02", input.MeasurementDate); err != nil {
		return nil, fmt.Errorf("invalid measurementDate: %w", err)
	}

	req := &profilev1.RecordMeasurementRequest{
		Measurement: &profilev1.Measurement{
			UserId:            uc.UserID,
			MeasurementDate:   input.MeasurementDate,
			WeightKg:          getFloatValue(input.WeightKg),
			BodyFatPercentage: getFloatValue(input.BodyFatPercentage),
			MuscleMassKg:      getFloatValue(input.MuscleMassKg),
			MeasurementsJson:  getStringValue(input.MeasurementsJSON),
		},
	}

	resp, err := r.ProfileClient.RecordMeasurement(ctx, req)
	if err != nil {
		return nil, err
	}
	return convertMeasurement(resp), nil
}

// ToggleFeedLike is the resolver for the toggleFeedLike field.
func (r *mutationResolver) ToggleFeedLike(ctx context.Context, postID string) (*model.FeedPost, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	_, err := r.WorkoutClient.ToggleFeedLike(ctx, &workoutv1.ToggleFeedLikeRequest{
		PostId: postID,
		UserId: uc.UserID,
	})
	if err != nil {
		return nil, err
	}

	post, err := r.WorkoutClient.GetFeedPost(ctx, &workoutv1.GetFeedPostRequest{
		PostId: postID,
		UserId: uc.UserID,
	})
	if err != nil {
		return nil, err
	}

	profiles, err := r.fetchProfiles(ctx, []string{post.GetUserId()})
	if err != nil {
		return nil, err
	}

	return convertFeedPost(post, profiles[post.GetUserId()]), nil
}

// AddFeedComment is the resolver for the addFeedComment field.
func (r *mutationResolver) AddFeedComment(ctx context.Context, postID string, body string) (*model.PostComment, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}
	if body == "" {
		return nil, fmt.Errorf("body is required")
	}

	resp, err := r.WorkoutClient.AddFeedComment(ctx, &workoutv1.AddFeedCommentRequest{
		PostId: postID,
		UserId: uc.UserID,
		Body:   body,
	})
	if err != nil {
		return nil, err
	}

	profileResp, err := r.ProfileClient.GetProfile(ctx, &profilev1.GetProfileRequest{UserId: uc.UserID})
	if err != nil {
		return nil, err
	}

	return convertFeedComment(resp, profileResp.GetProfile()), nil
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, notificationID string) (*model.Notification, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	resp, err := r.NotificationClient.MarkNotificationRead(ctx, &notificationv1.MarkNotificationReadRequest{
		NotificationId: notificationID,
		UserId:         uc.UserID,
	})
	if err != nil {
		return nil, err
	}
	return convertNotification(resp), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	profile, _ := r.ProfileClient.GetProfile(ctx, &profilev1.GetProfileRequest{UserId: uc.UserID})
	var profileModel *model.Profile
	if profile != nil && profile.GetProfile() != nil {
		profileModel = convertProfile(profile.GetProfile())
	}

	email := fmt.Sprintf("%s@zenx.local", uc.UserID)
	return &model.User{
		ID:          uc.UserID,
		Email:       email,
		DisplayName: extractDisplayName(profileModel),
		Profile:     profileModel,
	}, nil
}

// Workouts is the resolver for the workouts field.
func (r *queryResolver) Workouts(ctx context.Context, limit *int, after *string) ([]*model.Workout, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	req := &workoutv1.ListWorkoutsRequest{UserId: uc.UserID}
	if limit != nil || after != nil {
		req.Pagination = &commonv1.Pagination{}
		if limit != nil {
			req.Pagination.Limit = int32(*limit)
		}
		if after != nil {
			req.Pagination.Cursor = *after
		}
	}

	resp, err := r.WorkoutClient.ListWorkouts(ctx, req)
	if err != nil {
		return nil, err
	}

	var result []*model.Workout
	for _, w := range resp.GetWorkouts() {
		result = append(result, convertWorkout(w))
	}
	return result, nil
}

// Exercises is the resolver for the exercises field.
func (r *queryResolver) Exercises(ctx context.Context, query *string, category *string) ([]*model.Exercise, error) {
	req := &exercisev1.ListExercisesRequest{}
	if query != nil {
		req.Query = *query
	}
	resp, err := r.ExerciseClient.ListExercises(ctx, req)
	if err != nil {
		return nil, err
	}
	var result []*model.Exercise
	for _, ex := range resp.GetExercises() {
		exCategory := nullableString(ex.GetCategory())
		// Client-side category filtering
		if category != nil && exCategory != nil && strings.ToLower(*exCategory) != strings.ToLower(*category) {
			continue
		}
		result = append(result, &model.Exercise{
			ID:                    ex.GetId(),
			Name:                  ex.GetName(),
			Description:           nullableString(ex.GetDescription()),
			Category:              exCategory,
			PrimaryMuscleGroup:    nullableString(ex.GetPrimaryMuscleGroup()),
			SecondaryMuscleGroups: ex.GetSecondaryMuscleGroups(),
			EquipmentRequired:     nullableString(ex.GetEquipmentRequired()),
			DifficultyLevel:       nullableString(ex.GetDifficultyLevel()),
			IsCustom:              ex.GetIsCustom(),
		})
	}
	return result, nil
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*model.Profile, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}
	resp, err := r.ProfileClient.GetProfile(ctx, &profilev1.GetProfileRequest{UserId: uc.UserID})
	if err != nil {
		// If profile doesn't exist, return nil instead of error
		// The profile service should create a default profile on first access
		return nil, nil
	}
	if resp.GetProfile() == nil {
		return nil, nil
	}
	return convertProfile(resp.GetProfile()), nil
}

// ProgressSnapshot is the resolver for the progressSnapshot field.
func (r *queryResolver) ProgressSnapshot(ctx context.Context) (*model.ProgressSnapshot, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}
	resp, err := r.AnalyticsClient.GetProgressSnapshot(ctx, &analyticsv1.GetProgressSnapshotRequest{UserId: uc.UserID})
	if err != nil {
		return nil, err
	}
	if resp == nil {
		return nil, nil
	}

	exerciseMap, err := r.fetchExercises(ctx, collectRecordExerciseIDs(resp.GetPrs()))
	if err != nil {
		return nil, err
	}

	snapshot := &model.ProgressSnapshot{
		UserID:        resp.GetUserId(),
		CapturedAt:    time.Unix(resp.GetCapturedAt(), 0).UTC().Format(time.RFC3339),
		TotalVolumeKg: nullableFloat(resp.GetTotalVolumeKg()),
		AverageRpe:    nullableFloat(resp.GetAverageRpe()),
		WorkoutCount:  int(resp.GetWorkoutCount()),
	}
	for _, pr := range resp.GetPrs() {
		snapshot.Prs = append(snapshot.Prs, convertPersonalRecord(pr, convertExerciseProto(exerciseMap[pr.GetExerciseId()])))
	}
	return snapshot, nil
}

// PersonalRecords is the resolver for the personalRecords field.
func (r *queryResolver) PersonalRecords(ctx context.Context) ([]*model.PersonalRecord, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}
	resp, err := r.AnalyticsClient.ListPersonalRecords(ctx, &analyticsv1.ListPersonalRecordsRequest{UserId: uc.UserID})
	if err != nil {
		return nil, err
	}
	exerciseMap, err := r.fetchExercises(ctx, collectRecordExerciseIDs(resp.GetRecords()))
	if err != nil {
		return nil, err
	}

	var records []*model.PersonalRecord
	for _, pr := range resp.GetRecords() {
		records = append(records, convertPersonalRecord(pr, convertExerciseProto(exerciseMap[pr.GetExerciseId()])))
	}
	return records, nil
}

// Measurements is the resolver for the measurements field.
func (r *queryResolver) Measurements(ctx context.Context, rangeArg *model.MeasurementRangeInput) ([]*model.Measurement, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	req := &profilev1.ListMeasurementsRequest{UserId: uc.UserID}
	if rangeArg != nil {
		rng, err := buildTimestampRange(rangeArg)
		if err != nil {
			return nil, err
		}
		if rng != nil {
			req.Range = rng
		}
	}

	resp, err := r.ProfileClient.ListMeasurements(ctx, req)
	if err != nil {
		return nil, err
	}

	var result []*model.Measurement
	for _, m := range resp.GetMeasurements() {
		result = append(result, convertMeasurement(m))
	}
	return result, nil
}

// Feed is the resolver for the feed field.
func (r *queryResolver) Feed(ctx context.Context, limit *int, cursor *string) (*model.FeedConnection, error) {
	return r.feedConnection(ctx, limit, cursor, false)
}

// DiscoverFeed is the resolver for the discoverFeed field.
func (r *queryResolver) DiscoverFeed(ctx context.Context, limit *int, cursor *string) (*model.FeedConnection, error) {
	return r.feedConnection(ctx, limit, cursor, true)
}

// FeedComments is the resolver for the feedComments field.
func (r *queryResolver) FeedComments(ctx context.Context, postID string, limit *int, cursor *string) (*model.FeedCommentConnection, error) {
	req := &workoutv1.ListFeedCommentsRequest{PostId: postID}
	if pagination := buildPagination(limit, cursor); pagination != nil {
		req.Pagination = pagination
	}

	resp, err := r.WorkoutClient.ListFeedComments(ctx, req)
	if err != nil {
		return nil, err
	}

	userIDs := make([]string, 0, len(resp.GetComments()))
	for _, c := range resp.GetComments() {
		userIDs = append(userIDs, c.GetUserId())
	}
	profiles, err := r.fetchProfiles(ctx, userIDs)
	if err != nil {
		return nil, err
	}

	connection := &model.FeedCommentConnection{}
	for _, c := range resp.GetComments() {
		connection.Comments = append(connection.Comments, convertFeedComment(c, profiles[c.GetUserId()]))
	}
	if resp.GetNextCursor() != "" {
		connection.NextCursor = nullableString(resp.GetNextCursor())
	}
	return connection, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, limit *int, cursor *string, status *string) (*model.NotificationConnection, error) {
	uc, ok := GetUserContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	req := &notificationv1.ListNotificationsRequest{UserId: uc.UserID}
	if status != nil && *status != "" {
		req.Status = *status
	}
	if pagination := buildPagination(limit, cursor); pagination != nil {
		req.Pagination = pagination
	}

	resp, err := r.NotificationClient.ListNotifications(ctx, req)
	if err != nil {
		return nil, err
	}

	conn := &model.NotificationConnection{}
	for _, notif := range resp.GetNotifications() {
		conn.Nodes = append(conn.Nodes, convertNotification(notif))
	}
	if resp.GetNextCursor() != "" {
		conn.NextCursor = nullableString(resp.GetNextCursor())
	}
	return conn, nil
}

// WorkoutCalendar is the resolver for the workoutCalendar field.
func (r *queryResolver) WorkoutCalendar(ctx context.Context, startDate string, endDate string) (*model.WorkoutCalendar, error) {
	uc, err := getUserContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.AnalyticsClient.GetWorkoutCalendar(ctx, &analyticsv1.GetWorkoutCalendarRequest{
		UserId: uc.UserID,
		DateRange: &analyticsv1.DateRange{
			StartDate: startDate,
			EndDate:   endDate,
		},
	})
	if err != nil {
		return nil, err
	}

	return &model.WorkoutCalendar{
		StartDate:     startDate,
		EndDate:       endDate,
		WorkoutDays:   resp.GetWorkoutDays(),
		TotalWorkouts: int(resp.GetTotalWorkouts()),
	}, nil
}

// MuscleGroupStats is the resolver for the muscleGroupStats field.
func (r *queryResolver) MuscleGroupStats(ctx context.Context, dateRange *model.DateRangeInput) ([]*model.MuscleGroupStat, error) {
	uc, err := getUserContext(ctx)
	if err != nil {
		return nil, err
	}

	req := &analyticsv1.GetMuscleGroupStatsRequest{
		UserId: uc.UserID,
	}
	if dateRange != nil {
		req.DateRange = &analyticsv1.DateRange{
			StartDate: dateRange.StartDate,
			EndDate:   dateRange.EndDate,
		}
	}

	resp, err := r.AnalyticsClient.GetMuscleGroupStats(ctx, req)
	if err != nil {
		return nil, err
	}

	var stats []*model.MuscleGroupStat
	for _, s := range resp.GetStats() {
		stats = append(stats, &model.MuscleGroupStat{
			MuscleGroup: s.GetMuscleGroup(),
			SetCount:    int(s.GetSetCount()),
			Volume:      s.GetVolumeKg(),
			Percentage:  s.GetPercentage(),
		})
	}
	return stats, nil
}

// TopExercises is the resolver for the topExercises field.
func (r *queryResolver) TopExercises(ctx context.Context, limit *int, dateRange *model.DateRangeInput) ([]*model.ExerciseRecord, error) {
	uc, err := getUserContext(ctx)
	if err != nil {
		return nil, err
	}

	req := &analyticsv1.GetTopExercisesRequest{
		UserId: uc.UserID,
	}
	if limit != nil {
		req.Limit = int32(*limit)
	}
	if dateRange != nil {
		req.DateRange = &analyticsv1.DateRange{
			StartDate: dateRange.StartDate,
			EndDate:   dateRange.EndDate,
		}
	}

	resp, err := r.AnalyticsClient.GetTopExercises(ctx, req)
	if err != nil {
		return nil, err
	}

	var exercises []*model.ExerciseRecord
	for _, e := range resp.GetExercises() {
		exercises = append(exercises, &model.ExerciseRecord{
			ExerciseID:    e.GetExerciseId(),
			ExerciseName:  e.GetExerciseName(),
			WorkoutCount:  int(e.GetWorkoutCount()),
			LastPerformed: nullableString(e.GetLastPerformed()),
			// AverageWeight: nullableFloat(e.GetAverageWeight()), // Not in proto yet
		})
	}
	return exercises, nil
}

// ExercisePerformance is the resolver for the exercisePerformance field.
func (r *queryResolver) ExercisePerformance(ctx context.Context, exerciseID string) (*model.ExercisePerformance, error) {
	uc, err := getUserContext(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.AnalyticsClient.GetExerciseStats(ctx, &analyticsv1.GetExerciseStatsRequest{
		UserId:     uc.UserID,
		ExerciseId: exerciseID,
	})
	if err != nil {
		return nil, err
	}

	stats := resp.GetStats()
	if stats == nil {
		return nil, nil
	}

	var history []*model.WorkoutExerciseEntry
	for _, h := range stats.GetHistory() {
		history = append(history, &model.WorkoutExerciseEntry{
			WorkoutID: h.GetWorkoutId(),
			Date:      h.GetDate(),
			Weight:    h.GetWeight(),
			Reps:      int(h.GetReps()),
			OneRM:     nullableFloat(h.GetOneRm()),
			Volume:    nullableFloat(h.GetVolume()),
		})
	}

	var prs []*model.PersonalRecord
	for _, pr := range stats.GetPersonalRecords() {
		prs = append(prs, &model.PersonalRecord{
			ExerciseID: pr.GetExerciseId(),
			RecordType: pr.GetRecordType(),
			Value:      pr.GetValue(),
			AchievedAt: formatUnix(pr.GetAchievedAt()),
		})
	}

	return &model.ExercisePerformance{
		ExerciseID:        stats.GetExerciseId(),
		ExerciseName:      stats.GetExerciseName(),
		HeaviestWeight:    nullableFloat(stats.GetHeaviestWeight()),
		ProjectedOneRM:    nullableFloat(stats.GetProjectedOneRm()),
		BestSetVolume:     nullableFloat(stats.GetBestSetVolume()),
		BestSessionVolume: nullableFloat(stats.GetBestSessionVolume()),
		MostReps:          nullableInt(stats.GetMostReps()),
		PersonalRecords:   prs,
		History:           history,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
