// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: profile/v1/profile.proto

package profilev1

import (
	v1 "github.com/zenx/backend/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Profile) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *Profile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type Measurement struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MeasurementDate   string                 `protobuf:"bytes,3,opt,name=measurement_date,json=measurementDate,proto3" json:"measurement_date,omitempty"`
	WeightKg          float64                `protobuf:"fixed64,4,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	BodyFatPercentage float64                `protobuf:"fixed64,5,opt,name=body_fat_percentage,json=bodyFatPercentage,proto3" json:"body_fat_percentage,omitempty"`
	MuscleMassKg      float64                `protobuf:"fixed64,6,opt,name=muscle_mass_kg,json=muscleMassKg,proto3" json:"muscle_mass_kg,omitempty"`
	MeasurementsJson  string                 `protobuf:"bytes,7,opt,name=measurements_json,json=measurementsJson,proto3" json:"measurements_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *Measurement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Measurement) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Measurement) GetMeasurementDate() string {
	if x != nil {
		return x.MeasurementDate
	}
	return ""
}

func (x *Measurement) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *Measurement) GetBodyFatPercentage() float64 {
	if x != nil {
		return x.BodyFatPercentage
	}
	return 0
}

func (x *Measurement) GetMuscleMassKg() float64 {
	if x != nil {
		return x.MuscleMassKg
	}
	return 0
}

func (x *Measurement) GetMeasurementsJson() string {
	if x != nil {
		return x.MeasurementsJson
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type RecordMeasurementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Measurement   *Measurement           `protobuf:"bytes,1,opt,name=measurement,proto3" json:"measurement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordMeasurementRequest) Reset() {
	*x = RecordMeasurementRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMeasurementRequest) ProtoMessage() {}

func (x *RecordMeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMeasurementRequest.ProtoReflect.Descriptor instead.
func (*RecordMeasurementRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{5}
}

func (x *RecordMeasurementRequest) GetMeasurement() *Measurement {
	if x != nil {
		return x.Measurement
	}
	return nil
}

type ListMeasurementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Range         *v1.TimestampRange     `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeasurementsRequest) Reset() {
	*x = ListMeasurementsRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeasurementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeasurementsRequest) ProtoMessage() {}

func (x *ListMeasurementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeasurementsRequest.ProtoReflect.Descriptor instead.
func (*ListMeasurementsRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{6}
}

func (x *ListMeasurementsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListMeasurementsRequest) GetRange() *v1.TimestampRange {
	if x != nil {
		return x.Range
	}
	return nil
}

type ListMeasurementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Measurements  []*Measurement         `protobuf:"bytes,1,rep,name=measurements,proto3" json:"measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeasurementsResponse) Reset() {
	*x = ListMeasurementsResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeasurementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeasurementsResponse) ProtoMessage() {}

func (x *ListMeasurementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeasurementsResponse.ProtoReflect.Descriptor instead.
func (*ListMeasurementsResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{7}
}

func (x *ListMeasurementsResponse) GetMeasurements() []*Measurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

var File_profile_v1_profile_proto protoreflect.FileDescriptor

const file_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x18profile/v1/profile.proto\x12\x0fzenx.profile.v1\x1a\x16common/v1/common.proto\"\xc2\x01\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\"\n" +
	"\rdate_of_birth\x18\x06 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\"\x81\x02\n" +
	"\vMeasurement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x10measurement_date\x18\x03 \x01(\tR\x0fmeasurementDate\x12\x1b\n" +
	"\tweight_kg\x18\x04 \x01(\x01R\bweightKg\x12.\n" +
	"\x13body_fat_percentage\x18\x05 \x01(\x01R\x11bodyFatPercentage\x12$\n" +
	"\x0emuscle_mass_kg\x18\x06 \x01(\x01R\fmuscleMassKg\x12+\n" +
	"\x11measurements_json\x18\a \x01(\tR\x10measurementsJson\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x12GetProfileResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.zenx.profile.v1.ProfileR\aprofile\"J\n" +
	"\x14UpdateProfileRequest\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.zenx.profile.v1.ProfileR\aprofile\"Z\n" +
	"\x18RecordMeasurementRequest\x12>\n" +
	"\vmeasurement\x18\x01 \x01(\v2\x1c.zenx.profile.v1.MeasurementR\vmeasurement\"h\n" +
	"\x17ListMeasurementsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x124\n" +
	"\x05range\x18\x02 \x01(\v2\x1e.zenx.common.v1.TimestampRangeR\x05range\"\\\n" +
	"\x18ListMeasurementsResponse\x12@\n" +
	"\fmeasurements\x18\x01 \x03(\v2\x1c.zenx.profile.v1.MeasurementR\fmeasurements2\x80\x03\n" +
	"\x0eProfileService\x12U\n" +
	"\n" +
	"GetProfile\x12\".zenx.profile.v1.GetProfileRequest\x1a#.zenx.profile.v1.GetProfileResponse\x12P\n" +
	"\rUpdateProfile\x12%.zenx.profile.v1.UpdateProfileRequest\x1a\x18.zenx.profile.v1.Profile\x12\\\n" +
	"\x11RecordMeasurement\x12).zenx.profile.v1.RecordMeasurementRequest\x1a\x1c.zenx.profile.v1.Measurement\x12g\n" +
	"\x10ListMeasurements\x12(.zenx.profile.v1.ListMeasurementsRequest\x1a).zenx.profile.v1.ListMeasurementsResponseB4Z2github.com/zenx/backend/proto/profile/v1;profilev1b\x06proto3"

var (
	file_profile_v1_profile_proto_rawDescOnce sync.Once
	file_profile_v1_profile_proto_rawDescData []byte
)

func file_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)))
	})
	return file_profile_v1_profile_proto_rawDescData
}

var file_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_profile_v1_profile_proto_goTypes = []any{
	(*Profile)(nil),                  // 0: zenx.profile.v1.Profile
	(*Measurement)(nil),              // 1: zenx.profile.v1.Measurement
	(*GetProfileRequest)(nil),        // 2: zenx.profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil),       // 3: zenx.profile.v1.GetProfileResponse
	(*UpdateProfileRequest)(nil),     // 4: zenx.profile.v1.UpdateProfileRequest
	(*RecordMeasurementRequest)(nil), // 5: zenx.profile.v1.RecordMeasurementRequest
	(*ListMeasurementsRequest)(nil),  // 6: zenx.profile.v1.ListMeasurementsRequest
	(*ListMeasurementsResponse)(nil), // 7: zenx.profile.v1.ListMeasurementsResponse
	(*v1.TimestampRange)(nil),        // 8: zenx.common.v1.TimestampRange
}
var file_profile_v1_profile_proto_depIdxs = []int32{
	0, // 0: zenx.profile.v1.GetProfileResponse.profile:type_name -> zenx.profile.v1.Profile
	0, // 1: zenx.profile.v1.UpdateProfileRequest.profile:type_name -> zenx.profile.v1.Profile
	1, // 2: zenx.profile.v1.RecordMeasurementRequest.measurement:type_name -> zenx.profile.v1.Measurement
	8, // 3: zenx.profile.v1.ListMeasurementsRequest.range:type_name -> zenx.common.v1.TimestampRange
	1, // 4: zenx.profile.v1.ListMeasurementsResponse.measurements:type_name -> zenx.profile.v1.Measurement
	2, // 5: zenx.profile.v1.ProfileService.GetProfile:input_type -> zenx.profile.v1.GetProfileRequest
	4, // 6: zenx.profile.v1.ProfileService.UpdateProfile:input_type -> zenx.profile.v1.UpdateProfileRequest
	5, // 7: zenx.profile.v1.ProfileService.RecordMeasurement:input_type -> zenx.profile.v1.RecordMeasurementRequest
	6, // 8: zenx.profile.v1.ProfileService.ListMeasurements:input_type -> zenx.profile.v1.ListMeasurementsRequest
	3, // 9: zenx.profile.v1.ProfileService.GetProfile:output_type -> zenx.profile.v1.GetProfileResponse
	0, // 10: zenx.profile.v1.ProfileService.UpdateProfile:output_type -> zenx.profile.v1.Profile
	1, // 11: zenx.profile.v1.ProfileService.RecordMeasurement:output_type -> zenx.profile.v1.Measurement
	7, // 12: zenx.profile.v1.ProfileService.ListMeasurements:output_type -> zenx.profile.v1.ListMeasurementsResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_profile_v1_profile_proto_init() }
func file_profile_v1_profile_proto_init() {
	if File_profile_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_profile_v1_profile_proto_depIdxs,
		MessageInfos:      file_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_profile_v1_profile_proto = out.File
	file_profile_v1_profile_proto_goTypes = nil
	file_profile_v1_profile_proto_depIdxs = nil
}
