// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: profile/v1/profile.proto

package profilev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v11 "github.com/zenx/backend/proto/common/v1"
	v1 "github.com/zenx/backend/proto/profile/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProfileServiceName is the fully-qualified name of the ProfileService service.
	ProfileServiceName = "zenx.profile.v1.ProfileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProfileServiceGetProfileProcedure is the fully-qualified name of the ProfileService's GetProfile
	// RPC.
	ProfileServiceGetProfileProcedure = "/zenx.profile.v1.ProfileService/GetProfile"
	// ProfileServiceUpdateProfileProcedure is the fully-qualified name of the ProfileService's
	// UpdateProfile RPC.
	ProfileServiceUpdateProfileProcedure = "/zenx.profile.v1.ProfileService/UpdateProfile"
	// ProfileServiceRecordMeasurementProcedure is the fully-qualified name of the ProfileService's
	// RecordMeasurement RPC.
	ProfileServiceRecordMeasurementProcedure = "/zenx.profile.v1.ProfileService/RecordMeasurement"
	// ProfileServiceListMeasurementsProcedure is the fully-qualified name of the ProfileService's
	// ListMeasurements RPC.
	ProfileServiceListMeasurementsProcedure = "/zenx.profile.v1.ProfileService/ListMeasurements"
	// ProfileServiceDeleteProfileProcedure is the fully-qualified name of the ProfileService's
	// DeleteProfile RPC.
	ProfileServiceDeleteProfileProcedure = "/zenx.profile.v1.ProfileService/DeleteProfile"
)

// ProfileServiceClient is a client for the zenx.profile.v1.ProfileService service.
type ProfileServiceClient interface {
	GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error)
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.Profile], error)
	RecordMeasurement(context.Context, *connect.Request[v1.RecordMeasurementRequest]) (*connect.Response[v1.Measurement], error)
	ListMeasurements(context.Context, *connect.Request[v1.ListMeasurementsRequest]) (*connect.Response[v1.ListMeasurementsResponse], error)
	DeleteProfile(context.Context, *connect.Request[v1.DeleteProfileRequest]) (*connect.Response[v11.Empty], error)
}

// NewProfileServiceClient constructs a client for the zenx.profile.v1.ProfileService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProfileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProfileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	profileServiceMethods := v1.File_profile_v1_profile_proto.Services().ByName("ProfileService").Methods()
	return &profileServiceClient{
		getProfile: connect.NewClient[v1.GetProfileRequest, v1.GetProfileResponse](
			httpClient,
			baseURL+ProfileServiceGetProfileProcedure,
			connect.WithSchema(profileServiceMethods.ByName("GetProfile")),
			connect.WithClientOptions(opts...),
		),
		updateProfile: connect.NewClient[v1.UpdateProfileRequest, v1.Profile](
			httpClient,
			baseURL+ProfileServiceUpdateProfileProcedure,
			connect.WithSchema(profileServiceMethods.ByName("UpdateProfile")),
			connect.WithClientOptions(opts...),
		),
		recordMeasurement: connect.NewClient[v1.RecordMeasurementRequest, v1.Measurement](
			httpClient,
			baseURL+ProfileServiceRecordMeasurementProcedure,
			connect.WithSchema(profileServiceMethods.ByName("RecordMeasurement")),
			connect.WithClientOptions(opts...),
		),
		listMeasurements: connect.NewClient[v1.ListMeasurementsRequest, v1.ListMeasurementsResponse](
			httpClient,
			baseURL+ProfileServiceListMeasurementsProcedure,
			connect.WithSchema(profileServiceMethods.ByName("ListMeasurements")),
			connect.WithClientOptions(opts...),
		),
		deleteProfile: connect.NewClient[v1.DeleteProfileRequest, v11.Empty](
			httpClient,
			baseURL+ProfileServiceDeleteProfileProcedure,
			connect.WithSchema(profileServiceMethods.ByName("DeleteProfile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// profileServiceClient implements ProfileServiceClient.
type profileServiceClient struct {
	getProfile        *connect.Client[v1.GetProfileRequest, v1.GetProfileResponse]
	updateProfile     *connect.Client[v1.UpdateProfileRequest, v1.Profile]
	recordMeasurement *connect.Client[v1.RecordMeasurementRequest, v1.Measurement]
	listMeasurements  *connect.Client[v1.ListMeasurementsRequest, v1.ListMeasurementsResponse]
	deleteProfile     *connect.Client[v1.DeleteProfileRequest, v11.Empty]
}

// GetProfile calls zenx.profile.v1.ProfileService.GetProfile.
func (c *profileServiceClient) GetProfile(ctx context.Context, req *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error) {
	return c.getProfile.CallUnary(ctx, req)
}

// UpdateProfile calls zenx.profile.v1.ProfileService.UpdateProfile.
func (c *profileServiceClient) UpdateProfile(ctx context.Context, req *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.Profile], error) {
	return c.updateProfile.CallUnary(ctx, req)
}

// RecordMeasurement calls zenx.profile.v1.ProfileService.RecordMeasurement.
func (c *profileServiceClient) RecordMeasurement(ctx context.Context, req *connect.Request[v1.RecordMeasurementRequest]) (*connect.Response[v1.Measurement], error) {
	return c.recordMeasurement.CallUnary(ctx, req)
}

// ListMeasurements calls zenx.profile.v1.ProfileService.ListMeasurements.
func (c *profileServiceClient) ListMeasurements(ctx context.Context, req *connect.Request[v1.ListMeasurementsRequest]) (*connect.Response[v1.ListMeasurementsResponse], error) {
	return c.listMeasurements.CallUnary(ctx, req)
}

// DeleteProfile calls zenx.profile.v1.ProfileService.DeleteProfile.
func (c *profileServiceClient) DeleteProfile(ctx context.Context, req *connect.Request[v1.DeleteProfileRequest]) (*connect.Response[v11.Empty], error) {
	return c.deleteProfile.CallUnary(ctx, req)
}

// ProfileServiceHandler is an implementation of the zenx.profile.v1.ProfileService service.
type ProfileServiceHandler interface {
	GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error)
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.Profile], error)
	RecordMeasurement(context.Context, *connect.Request[v1.RecordMeasurementRequest]) (*connect.Response[v1.Measurement], error)
	ListMeasurements(context.Context, *connect.Request[v1.ListMeasurementsRequest]) (*connect.Response[v1.ListMeasurementsResponse], error)
	DeleteProfile(context.Context, *connect.Request[v1.DeleteProfileRequest]) (*connect.Response[v11.Empty], error)
}

// NewProfileServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProfileServiceHandler(svc ProfileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	profileServiceMethods := v1.File_profile_v1_profile_proto.Services().ByName("ProfileService").Methods()
	profileServiceGetProfileHandler := connect.NewUnaryHandler(
		ProfileServiceGetProfileProcedure,
		svc.GetProfile,
		connect.WithSchema(profileServiceMethods.ByName("GetProfile")),
		connect.WithHandlerOptions(opts...),
	)
	profileServiceUpdateProfileHandler := connect.NewUnaryHandler(
		ProfileServiceUpdateProfileProcedure,
		svc.UpdateProfile,
		connect.WithSchema(profileServiceMethods.ByName("UpdateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	profileServiceRecordMeasurementHandler := connect.NewUnaryHandler(
		ProfileServiceRecordMeasurementProcedure,
		svc.RecordMeasurement,
		connect.WithSchema(profileServiceMethods.ByName("RecordMeasurement")),
		connect.WithHandlerOptions(opts...),
	)
	profileServiceListMeasurementsHandler := connect.NewUnaryHandler(
		ProfileServiceListMeasurementsProcedure,
		svc.ListMeasurements,
		connect.WithSchema(profileServiceMethods.ByName("ListMeasurements")),
		connect.WithHandlerOptions(opts...),
	)
	profileServiceDeleteProfileHandler := connect.NewUnaryHandler(
		ProfileServiceDeleteProfileProcedure,
		svc.DeleteProfile,
		connect.WithSchema(profileServiceMethods.ByName("DeleteProfile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/zenx.profile.v1.ProfileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProfileServiceGetProfileProcedure:
			profileServiceGetProfileHandler.ServeHTTP(w, r)
		case ProfileServiceUpdateProfileProcedure:
			profileServiceUpdateProfileHandler.ServeHTTP(w, r)
		case ProfileServiceRecordMeasurementProcedure:
			profileServiceRecordMeasurementHandler.ServeHTTP(w, r)
		case ProfileServiceListMeasurementsProcedure:
			profileServiceListMeasurementsHandler.ServeHTTP(w, r)
		case ProfileServiceDeleteProfileProcedure:
			profileServiceDeleteProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProfileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProfileServiceHandler struct{}

func (UnimplementedProfileServiceHandler) GetProfile(context.Context, *connect.Request[v1.GetProfileRequest]) (*connect.Response[v1.GetProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.profile.v1.ProfileService.GetProfile is not implemented"))
}

func (UnimplementedProfileServiceHandler) UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.Profile], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.profile.v1.ProfileService.UpdateProfile is not implemented"))
}

func (UnimplementedProfileServiceHandler) RecordMeasurement(context.Context, *connect.Request[v1.RecordMeasurementRequest]) (*connect.Response[v1.Measurement], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.profile.v1.ProfileService.RecordMeasurement is not implemented"))
}

func (UnimplementedProfileServiceHandler) ListMeasurements(context.Context, *connect.Request[v1.ListMeasurementsRequest]) (*connect.Response[v1.ListMeasurementsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.profile.v1.ProfileService.ListMeasurements is not implemented"))
}

func (UnimplementedProfileServiceHandler) DeleteProfile(context.Context, *connect.Request[v1.DeleteProfileRequest]) (*connect.Response[v11.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.profile.v1.ProfileService.DeleteProfile is not implemented"))
}
