// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: exercise/v1/exercise.proto

package exercisev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/zenx/backend/proto/exercise/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ExerciseServiceName is the fully-qualified name of the ExerciseService service.
	ExerciseServiceName = "zenx.exercise.v1.ExerciseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ExerciseServiceCreateExerciseProcedure is the fully-qualified name of the ExerciseService's
	// CreateExercise RPC.
	ExerciseServiceCreateExerciseProcedure = "/zenx.exercise.v1.ExerciseService/CreateExercise"
	// ExerciseServiceGetExerciseProcedure is the fully-qualified name of the ExerciseService's
	// GetExercise RPC.
	ExerciseServiceGetExerciseProcedure = "/zenx.exercise.v1.ExerciseService/GetExercise"
	// ExerciseServiceListExercisesProcedure is the fully-qualified name of the ExerciseService's
	// ListExercises RPC.
	ExerciseServiceListExercisesProcedure = "/zenx.exercise.v1.ExerciseService/ListExercises"
)

// ExerciseServiceClient is a client for the zenx.exercise.v1.ExerciseService service.
type ExerciseServiceClient interface {
	CreateExercise(context.Context, *connect.Request[v1.CreateExerciseRequest]) (*connect.Response[v1.Exercise], error)
	GetExercise(context.Context, *connect.Request[v1.GetExerciseRequest]) (*connect.Response[v1.Exercise], error)
	ListExercises(context.Context, *connect.Request[v1.ListExercisesRequest]) (*connect.Response[v1.ListExercisesResponse], error)
}

// NewExerciseServiceClient constructs a client for the zenx.exercise.v1.ExerciseService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExerciseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExerciseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	exerciseServiceMethods := v1.File_exercise_v1_exercise_proto.Services().ByName("ExerciseService").Methods()
	return &exerciseServiceClient{
		createExercise: connect.NewClient[v1.CreateExerciseRequest, v1.Exercise](
			httpClient,
			baseURL+ExerciseServiceCreateExerciseProcedure,
			connect.WithSchema(exerciseServiceMethods.ByName("CreateExercise")),
			connect.WithClientOptions(opts...),
		),
		getExercise: connect.NewClient[v1.GetExerciseRequest, v1.Exercise](
			httpClient,
			baseURL+ExerciseServiceGetExerciseProcedure,
			connect.WithSchema(exerciseServiceMethods.ByName("GetExercise")),
			connect.WithClientOptions(opts...),
		),
		listExercises: connect.NewClient[v1.ListExercisesRequest, v1.ListExercisesResponse](
			httpClient,
			baseURL+ExerciseServiceListExercisesProcedure,
			connect.WithSchema(exerciseServiceMethods.ByName("ListExercises")),
			connect.WithClientOptions(opts...),
		),
	}
}

// exerciseServiceClient implements ExerciseServiceClient.
type exerciseServiceClient struct {
	createExercise *connect.Client[v1.CreateExerciseRequest, v1.Exercise]
	getExercise    *connect.Client[v1.GetExerciseRequest, v1.Exercise]
	listExercises  *connect.Client[v1.ListExercisesRequest, v1.ListExercisesResponse]
}

// CreateExercise calls zenx.exercise.v1.ExerciseService.CreateExercise.
func (c *exerciseServiceClient) CreateExercise(ctx context.Context, req *connect.Request[v1.CreateExerciseRequest]) (*connect.Response[v1.Exercise], error) {
	return c.createExercise.CallUnary(ctx, req)
}

// GetExercise calls zenx.exercise.v1.ExerciseService.GetExercise.
func (c *exerciseServiceClient) GetExercise(ctx context.Context, req *connect.Request[v1.GetExerciseRequest]) (*connect.Response[v1.Exercise], error) {
	return c.getExercise.CallUnary(ctx, req)
}

// ListExercises calls zenx.exercise.v1.ExerciseService.ListExercises.
func (c *exerciseServiceClient) ListExercises(ctx context.Context, req *connect.Request[v1.ListExercisesRequest]) (*connect.Response[v1.ListExercisesResponse], error) {
	return c.listExercises.CallUnary(ctx, req)
}

// ExerciseServiceHandler is an implementation of the zenx.exercise.v1.ExerciseService service.
type ExerciseServiceHandler interface {
	CreateExercise(context.Context, *connect.Request[v1.CreateExerciseRequest]) (*connect.Response[v1.Exercise], error)
	GetExercise(context.Context, *connect.Request[v1.GetExerciseRequest]) (*connect.Response[v1.Exercise], error)
	ListExercises(context.Context, *connect.Request[v1.ListExercisesRequest]) (*connect.Response[v1.ListExercisesResponse], error)
}

// NewExerciseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExerciseServiceHandler(svc ExerciseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	exerciseServiceMethods := v1.File_exercise_v1_exercise_proto.Services().ByName("ExerciseService").Methods()
	exerciseServiceCreateExerciseHandler := connect.NewUnaryHandler(
		ExerciseServiceCreateExerciseProcedure,
		svc.CreateExercise,
		connect.WithSchema(exerciseServiceMethods.ByName("CreateExercise")),
		connect.WithHandlerOptions(opts...),
	)
	exerciseServiceGetExerciseHandler := connect.NewUnaryHandler(
		ExerciseServiceGetExerciseProcedure,
		svc.GetExercise,
		connect.WithSchema(exerciseServiceMethods.ByName("GetExercise")),
		connect.WithHandlerOptions(opts...),
	)
	exerciseServiceListExercisesHandler := connect.NewUnaryHandler(
		ExerciseServiceListExercisesProcedure,
		svc.ListExercises,
		connect.WithSchema(exerciseServiceMethods.ByName("ListExercises")),
		connect.WithHandlerOptions(opts...),
	)
	return "/zenx.exercise.v1.ExerciseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExerciseServiceCreateExerciseProcedure:
			exerciseServiceCreateExerciseHandler.ServeHTTP(w, r)
		case ExerciseServiceGetExerciseProcedure:
			exerciseServiceGetExerciseHandler.ServeHTTP(w, r)
		case ExerciseServiceListExercisesProcedure:
			exerciseServiceListExercisesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExerciseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExerciseServiceHandler struct{}

func (UnimplementedExerciseServiceHandler) CreateExercise(context.Context, *connect.Request[v1.CreateExerciseRequest]) (*connect.Response[v1.Exercise], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.exercise.v1.ExerciseService.CreateExercise is not implemented"))
}

func (UnimplementedExerciseServiceHandler) GetExercise(context.Context, *connect.Request[v1.GetExerciseRequest]) (*connect.Response[v1.Exercise], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.exercise.v1.ExerciseService.GetExercise is not implemented"))
}

func (UnimplementedExerciseServiceHandler) ListExercises(context.Context, *connect.Request[v1.ListExercisesRequest]) (*connect.Response[v1.ListExercisesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.exercise.v1.ExerciseService.ListExercises is not implemented"))
}
