// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: notification/v1/notification.proto

package notificationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/zenx/backend/proto/notification/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotificationServiceName is the fully-qualified name of the NotificationService service.
	NotificationServiceName = "zenx.notification.v1.NotificationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotificationServiceEnqueueNotificationProcedure is the fully-qualified name of the
	// NotificationService's EnqueueNotification RPC.
	NotificationServiceEnqueueNotificationProcedure = "/zenx.notification.v1.NotificationService/EnqueueNotification"
	// NotificationServiceUpdatePreferenceProcedure is the fully-qualified name of the
	// NotificationService's UpdatePreference RPC.
	NotificationServiceUpdatePreferenceProcedure = "/zenx.notification.v1.NotificationService/UpdatePreference"
	// NotificationServiceListPreferencesProcedure is the fully-qualified name of the
	// NotificationService's ListPreferences RPC.
	NotificationServiceListPreferencesProcedure = "/zenx.notification.v1.NotificationService/ListPreferences"
	// NotificationServiceListNotificationsProcedure is the fully-qualified name of the
	// NotificationService's ListNotifications RPC.
	NotificationServiceListNotificationsProcedure = "/zenx.notification.v1.NotificationService/ListNotifications"
	// NotificationServiceMarkNotificationReadProcedure is the fully-qualified name of the
	// NotificationService's MarkNotificationRead RPC.
	NotificationServiceMarkNotificationReadProcedure = "/zenx.notification.v1.NotificationService/MarkNotificationRead"
)

// NotificationServiceClient is a client for the zenx.notification.v1.NotificationService service.
type NotificationServiceClient interface {
	EnqueueNotification(context.Context, *connect.Request[v1.EnqueueNotificationRequest]) (*connect.Response[v1.EnqueueNotificationResponse], error)
	UpdatePreference(context.Context, *connect.Request[v1.UpdatePreferenceRequest]) (*connect.Response[v1.Preference], error)
	ListPreferences(context.Context, *connect.Request[v1.ListPreferencesRequest]) (*connect.Response[v1.ListPreferencesResponse], error)
	ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error)
	MarkNotificationRead(context.Context, *connect.Request[v1.MarkNotificationReadRequest]) (*connect.Response[v1.Notification], error)
}

// NewNotificationServiceClient constructs a client for the zenx.notification.v1.NotificationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notificationServiceMethods := v1.File_notification_v1_notification_proto.Services().ByName("NotificationService").Methods()
	return &notificationServiceClient{
		enqueueNotification: connect.NewClient[v1.EnqueueNotificationRequest, v1.EnqueueNotificationResponse](
			httpClient,
			baseURL+NotificationServiceEnqueueNotificationProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("EnqueueNotification")),
			connect.WithClientOptions(opts...),
		),
		updatePreference: connect.NewClient[v1.UpdatePreferenceRequest, v1.Preference](
			httpClient,
			baseURL+NotificationServiceUpdatePreferenceProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("UpdatePreference")),
			connect.WithClientOptions(opts...),
		),
		listPreferences: connect.NewClient[v1.ListPreferencesRequest, v1.ListPreferencesResponse](
			httpClient,
			baseURL+NotificationServiceListPreferencesProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("ListPreferences")),
			connect.WithClientOptions(opts...),
		),
		listNotifications: connect.NewClient[v1.ListNotificationsRequest, v1.ListNotificationsResponse](
			httpClient,
			baseURL+NotificationServiceListNotificationsProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("ListNotifications")),
			connect.WithClientOptions(opts...),
		),
		markNotificationRead: connect.NewClient[v1.MarkNotificationReadRequest, v1.Notification](
			httpClient,
			baseURL+NotificationServiceMarkNotificationReadProcedure,
			connect.WithSchema(notificationServiceMethods.ByName("MarkNotificationRead")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationServiceClient implements NotificationServiceClient.
type notificationServiceClient struct {
	enqueueNotification  *connect.Client[v1.EnqueueNotificationRequest, v1.EnqueueNotificationResponse]
	updatePreference     *connect.Client[v1.UpdatePreferenceRequest, v1.Preference]
	listPreferences      *connect.Client[v1.ListPreferencesRequest, v1.ListPreferencesResponse]
	listNotifications    *connect.Client[v1.ListNotificationsRequest, v1.ListNotificationsResponse]
	markNotificationRead *connect.Client[v1.MarkNotificationReadRequest, v1.Notification]
}

// EnqueueNotification calls zenx.notification.v1.NotificationService.EnqueueNotification.
func (c *notificationServiceClient) EnqueueNotification(ctx context.Context, req *connect.Request[v1.EnqueueNotificationRequest]) (*connect.Response[v1.EnqueueNotificationResponse], error) {
	return c.enqueueNotification.CallUnary(ctx, req)
}

// UpdatePreference calls zenx.notification.v1.NotificationService.UpdatePreference.
func (c *notificationServiceClient) UpdatePreference(ctx context.Context, req *connect.Request[v1.UpdatePreferenceRequest]) (*connect.Response[v1.Preference], error) {
	return c.updatePreference.CallUnary(ctx, req)
}

// ListPreferences calls zenx.notification.v1.NotificationService.ListPreferences.
func (c *notificationServiceClient) ListPreferences(ctx context.Context, req *connect.Request[v1.ListPreferencesRequest]) (*connect.Response[v1.ListPreferencesResponse], error) {
	return c.listPreferences.CallUnary(ctx, req)
}

// ListNotifications calls zenx.notification.v1.NotificationService.ListNotifications.
func (c *notificationServiceClient) ListNotifications(ctx context.Context, req *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error) {
	return c.listNotifications.CallUnary(ctx, req)
}

// MarkNotificationRead calls zenx.notification.v1.NotificationService.MarkNotificationRead.
func (c *notificationServiceClient) MarkNotificationRead(ctx context.Context, req *connect.Request[v1.MarkNotificationReadRequest]) (*connect.Response[v1.Notification], error) {
	return c.markNotificationRead.CallUnary(ctx, req)
}

// NotificationServiceHandler is an implementation of the zenx.notification.v1.NotificationService
// service.
type NotificationServiceHandler interface {
	EnqueueNotification(context.Context, *connect.Request[v1.EnqueueNotificationRequest]) (*connect.Response[v1.EnqueueNotificationResponse], error)
	UpdatePreference(context.Context, *connect.Request[v1.UpdatePreferenceRequest]) (*connect.Response[v1.Preference], error)
	ListPreferences(context.Context, *connect.Request[v1.ListPreferencesRequest]) (*connect.Response[v1.ListPreferencesResponse], error)
	ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error)
	MarkNotificationRead(context.Context, *connect.Request[v1.MarkNotificationReadRequest]) (*connect.Response[v1.Notification], error)
}

// NewNotificationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationServiceHandler(svc NotificationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationServiceMethods := v1.File_notification_v1_notification_proto.Services().ByName("NotificationService").Methods()
	notificationServiceEnqueueNotificationHandler := connect.NewUnaryHandler(
		NotificationServiceEnqueueNotificationProcedure,
		svc.EnqueueNotification,
		connect.WithSchema(notificationServiceMethods.ByName("EnqueueNotification")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceUpdatePreferenceHandler := connect.NewUnaryHandler(
		NotificationServiceUpdatePreferenceProcedure,
		svc.UpdatePreference,
		connect.WithSchema(notificationServiceMethods.ByName("UpdatePreference")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceListPreferencesHandler := connect.NewUnaryHandler(
		NotificationServiceListPreferencesProcedure,
		svc.ListPreferences,
		connect.WithSchema(notificationServiceMethods.ByName("ListPreferences")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceListNotificationsHandler := connect.NewUnaryHandler(
		NotificationServiceListNotificationsProcedure,
		svc.ListNotifications,
		connect.WithSchema(notificationServiceMethods.ByName("ListNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	notificationServiceMarkNotificationReadHandler := connect.NewUnaryHandler(
		NotificationServiceMarkNotificationReadProcedure,
		svc.MarkNotificationRead,
		connect.WithSchema(notificationServiceMethods.ByName("MarkNotificationRead")),
		connect.WithHandlerOptions(opts...),
	)
	return "/zenx.notification.v1.NotificationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationServiceEnqueueNotificationProcedure:
			notificationServiceEnqueueNotificationHandler.ServeHTTP(w, r)
		case NotificationServiceUpdatePreferenceProcedure:
			notificationServiceUpdatePreferenceHandler.ServeHTTP(w, r)
		case NotificationServiceListPreferencesProcedure:
			notificationServiceListPreferencesHandler.ServeHTTP(w, r)
		case NotificationServiceListNotificationsProcedure:
			notificationServiceListNotificationsHandler.ServeHTTP(w, r)
		case NotificationServiceMarkNotificationReadProcedure:
			notificationServiceMarkNotificationReadHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationServiceHandler struct{}

func (UnimplementedNotificationServiceHandler) EnqueueNotification(context.Context, *connect.Request[v1.EnqueueNotificationRequest]) (*connect.Response[v1.EnqueueNotificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.notification.v1.NotificationService.EnqueueNotification is not implemented"))
}

func (UnimplementedNotificationServiceHandler) UpdatePreference(context.Context, *connect.Request[v1.UpdatePreferenceRequest]) (*connect.Response[v1.Preference], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.notification.v1.NotificationService.UpdatePreference is not implemented"))
}

func (UnimplementedNotificationServiceHandler) ListPreferences(context.Context, *connect.Request[v1.ListPreferencesRequest]) (*connect.Response[v1.ListPreferencesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.notification.v1.NotificationService.ListPreferences is not implemented"))
}

func (UnimplementedNotificationServiceHandler) ListNotifications(context.Context, *connect.Request[v1.ListNotificationsRequest]) (*connect.Response[v1.ListNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.notification.v1.NotificationService.ListNotifications is not implemented"))
}

func (UnimplementedNotificationServiceHandler) MarkNotificationRead(context.Context, *connect.Request[v1.MarkNotificationReadRequest]) (*connect.Response[v1.Notification], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.notification.v1.NotificationService.MarkNotificationRead is not implemented"))
}
