// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: analytics/v1/analytics.proto

package analyticsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/zenx/backend/proto/analytics/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AnalyticsServiceName is the fully-qualified name of the AnalyticsService service.
	AnalyticsServiceName = "zenx.analytics.v1.AnalyticsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AnalyticsServiceGetProgressSnapshotProcedure is the fully-qualified name of the
	// AnalyticsService's GetProgressSnapshot RPC.
	AnalyticsServiceGetProgressSnapshotProcedure = "/zenx.analytics.v1.AnalyticsService/GetProgressSnapshot"
	// AnalyticsServiceListPersonalRecordsProcedure is the fully-qualified name of the
	// AnalyticsService's ListPersonalRecords RPC.
	AnalyticsServiceListPersonalRecordsProcedure = "/zenx.analytics.v1.AnalyticsService/ListPersonalRecords"
	// AnalyticsServiceRecalculateMetricsProcedure is the fully-qualified name of the AnalyticsService's
	// RecalculateMetrics RPC.
	AnalyticsServiceRecalculateMetricsProcedure = "/zenx.analytics.v1.AnalyticsService/RecalculateMetrics"
	// AnalyticsServiceGetWorkoutCalendarProcedure is the fully-qualified name of the AnalyticsService's
	// GetWorkoutCalendar RPC.
	AnalyticsServiceGetWorkoutCalendarProcedure = "/zenx.analytics.v1.AnalyticsService/GetWorkoutCalendar"
	// AnalyticsServiceGetMuscleGroupStatsProcedure is the fully-qualified name of the
	// AnalyticsService's GetMuscleGroupStats RPC.
	AnalyticsServiceGetMuscleGroupStatsProcedure = "/zenx.analytics.v1.AnalyticsService/GetMuscleGroupStats"
	// AnalyticsServiceGetTopExercisesProcedure is the fully-qualified name of the AnalyticsService's
	// GetTopExercises RPC.
	AnalyticsServiceGetTopExercisesProcedure = "/zenx.analytics.v1.AnalyticsService/GetTopExercises"
	// AnalyticsServiceGetExerciseStatsProcedure is the fully-qualified name of the AnalyticsService's
	// GetExerciseStats RPC.
	AnalyticsServiceGetExerciseStatsProcedure = "/zenx.analytics.v1.AnalyticsService/GetExerciseStats"
)

// AnalyticsServiceClient is a client for the zenx.analytics.v1.AnalyticsService service.
type AnalyticsServiceClient interface {
	GetProgressSnapshot(context.Context, *connect.Request[v1.GetProgressSnapshotRequest]) (*connect.Response[v1.ProgressSnapshot], error)
	ListPersonalRecords(context.Context, *connect.Request[v1.ListPersonalRecordsRequest]) (*connect.Response[v1.ListPersonalRecordsResponse], error)
	RecalculateMetrics(context.Context, *connect.Request[v1.RecalculateMetricsRequest]) (*connect.Response[v1.RecalculateMetricsResponse], error)
	// New analytics methods
	GetWorkoutCalendar(context.Context, *connect.Request[v1.GetWorkoutCalendarRequest]) (*connect.Response[v1.GetWorkoutCalendarResponse], error)
	GetMuscleGroupStats(context.Context, *connect.Request[v1.GetMuscleGroupStatsRequest]) (*connect.Response[v1.GetMuscleGroupStatsResponse], error)
	GetTopExercises(context.Context, *connect.Request[v1.GetTopExercisesRequest]) (*connect.Response[v1.GetTopExercisesResponse], error)
	GetExerciseStats(context.Context, *connect.Request[v1.GetExerciseStatsRequest]) (*connect.Response[v1.GetExerciseStatsResponse], error)
}

// NewAnalyticsServiceClient constructs a client for the zenx.analytics.v1.AnalyticsService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnalyticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AnalyticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	analyticsServiceMethods := v1.File_analytics_v1_analytics_proto.Services().ByName("AnalyticsService").Methods()
	return &analyticsServiceClient{
		getProgressSnapshot: connect.NewClient[v1.GetProgressSnapshotRequest, v1.ProgressSnapshot](
			httpClient,
			baseURL+AnalyticsServiceGetProgressSnapshotProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetProgressSnapshot")),
			connect.WithClientOptions(opts...),
		),
		listPersonalRecords: connect.NewClient[v1.ListPersonalRecordsRequest, v1.ListPersonalRecordsResponse](
			httpClient,
			baseURL+AnalyticsServiceListPersonalRecordsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("ListPersonalRecords")),
			connect.WithClientOptions(opts...),
		),
		recalculateMetrics: connect.NewClient[v1.RecalculateMetricsRequest, v1.RecalculateMetricsResponse](
			httpClient,
			baseURL+AnalyticsServiceRecalculateMetricsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("RecalculateMetrics")),
			connect.WithClientOptions(opts...),
		),
		getWorkoutCalendar: connect.NewClient[v1.GetWorkoutCalendarRequest, v1.GetWorkoutCalendarResponse](
			httpClient,
			baseURL+AnalyticsServiceGetWorkoutCalendarProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetWorkoutCalendar")),
			connect.WithClientOptions(opts...),
		),
		getMuscleGroupStats: connect.NewClient[v1.GetMuscleGroupStatsRequest, v1.GetMuscleGroupStatsResponse](
			httpClient,
			baseURL+AnalyticsServiceGetMuscleGroupStatsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetMuscleGroupStats")),
			connect.WithClientOptions(opts...),
		),
		getTopExercises: connect.NewClient[v1.GetTopExercisesRequest, v1.GetTopExercisesResponse](
			httpClient,
			baseURL+AnalyticsServiceGetTopExercisesProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetTopExercises")),
			connect.WithClientOptions(opts...),
		),
		getExerciseStats: connect.NewClient[v1.GetExerciseStatsRequest, v1.GetExerciseStatsResponse](
			httpClient,
			baseURL+AnalyticsServiceGetExerciseStatsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetExerciseStats")),
			connect.WithClientOptions(opts...),
		),
	}
}

// analyticsServiceClient implements AnalyticsServiceClient.
type analyticsServiceClient struct {
	getProgressSnapshot *connect.Client[v1.GetProgressSnapshotRequest, v1.ProgressSnapshot]
	listPersonalRecords *connect.Client[v1.ListPersonalRecordsRequest, v1.ListPersonalRecordsResponse]
	recalculateMetrics  *connect.Client[v1.RecalculateMetricsRequest, v1.RecalculateMetricsResponse]
	getWorkoutCalendar  *connect.Client[v1.GetWorkoutCalendarRequest, v1.GetWorkoutCalendarResponse]
	getMuscleGroupStats *connect.Client[v1.GetMuscleGroupStatsRequest, v1.GetMuscleGroupStatsResponse]
	getTopExercises     *connect.Client[v1.GetTopExercisesRequest, v1.GetTopExercisesResponse]
	getExerciseStats    *connect.Client[v1.GetExerciseStatsRequest, v1.GetExerciseStatsResponse]
}

// GetProgressSnapshot calls zenx.analytics.v1.AnalyticsService.GetProgressSnapshot.
func (c *analyticsServiceClient) GetProgressSnapshot(ctx context.Context, req *connect.Request[v1.GetProgressSnapshotRequest]) (*connect.Response[v1.ProgressSnapshot], error) {
	return c.getProgressSnapshot.CallUnary(ctx, req)
}

// ListPersonalRecords calls zenx.analytics.v1.AnalyticsService.ListPersonalRecords.
func (c *analyticsServiceClient) ListPersonalRecords(ctx context.Context, req *connect.Request[v1.ListPersonalRecordsRequest]) (*connect.Response[v1.ListPersonalRecordsResponse], error) {
	return c.listPersonalRecords.CallUnary(ctx, req)
}

// RecalculateMetrics calls zenx.analytics.v1.AnalyticsService.RecalculateMetrics.
func (c *analyticsServiceClient) RecalculateMetrics(ctx context.Context, req *connect.Request[v1.RecalculateMetricsRequest]) (*connect.Response[v1.RecalculateMetricsResponse], error) {
	return c.recalculateMetrics.CallUnary(ctx, req)
}

// GetWorkoutCalendar calls zenx.analytics.v1.AnalyticsService.GetWorkoutCalendar.
func (c *analyticsServiceClient) GetWorkoutCalendar(ctx context.Context, req *connect.Request[v1.GetWorkoutCalendarRequest]) (*connect.Response[v1.GetWorkoutCalendarResponse], error) {
	return c.getWorkoutCalendar.CallUnary(ctx, req)
}

// GetMuscleGroupStats calls zenx.analytics.v1.AnalyticsService.GetMuscleGroupStats.
func (c *analyticsServiceClient) GetMuscleGroupStats(ctx context.Context, req *connect.Request[v1.GetMuscleGroupStatsRequest]) (*connect.Response[v1.GetMuscleGroupStatsResponse], error) {
	return c.getMuscleGroupStats.CallUnary(ctx, req)
}

// GetTopExercises calls zenx.analytics.v1.AnalyticsService.GetTopExercises.
func (c *analyticsServiceClient) GetTopExercises(ctx context.Context, req *connect.Request[v1.GetTopExercisesRequest]) (*connect.Response[v1.GetTopExercisesResponse], error) {
	return c.getTopExercises.CallUnary(ctx, req)
}

// GetExerciseStats calls zenx.analytics.v1.AnalyticsService.GetExerciseStats.
func (c *analyticsServiceClient) GetExerciseStats(ctx context.Context, req *connect.Request[v1.GetExerciseStatsRequest]) (*connect.Response[v1.GetExerciseStatsResponse], error) {
	return c.getExerciseStats.CallUnary(ctx, req)
}

// AnalyticsServiceHandler is an implementation of the zenx.analytics.v1.AnalyticsService service.
type AnalyticsServiceHandler interface {
	GetProgressSnapshot(context.Context, *connect.Request[v1.GetProgressSnapshotRequest]) (*connect.Response[v1.ProgressSnapshot], error)
	ListPersonalRecords(context.Context, *connect.Request[v1.ListPersonalRecordsRequest]) (*connect.Response[v1.ListPersonalRecordsResponse], error)
	RecalculateMetrics(context.Context, *connect.Request[v1.RecalculateMetricsRequest]) (*connect.Response[v1.RecalculateMetricsResponse], error)
	// New analytics methods
	GetWorkoutCalendar(context.Context, *connect.Request[v1.GetWorkoutCalendarRequest]) (*connect.Response[v1.GetWorkoutCalendarResponse], error)
	GetMuscleGroupStats(context.Context, *connect.Request[v1.GetMuscleGroupStatsRequest]) (*connect.Response[v1.GetMuscleGroupStatsResponse], error)
	GetTopExercises(context.Context, *connect.Request[v1.GetTopExercisesRequest]) (*connect.Response[v1.GetTopExercisesResponse], error)
	GetExerciseStats(context.Context, *connect.Request[v1.GetExerciseStatsRequest]) (*connect.Response[v1.GetExerciseStatsResponse], error)
}

// NewAnalyticsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnalyticsServiceHandler(svc AnalyticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	analyticsServiceMethods := v1.File_analytics_v1_analytics_proto.Services().ByName("AnalyticsService").Methods()
	analyticsServiceGetProgressSnapshotHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetProgressSnapshotProcedure,
		svc.GetProgressSnapshot,
		connect.WithSchema(analyticsServiceMethods.ByName("GetProgressSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceListPersonalRecordsHandler := connect.NewUnaryHandler(
		AnalyticsServiceListPersonalRecordsProcedure,
		svc.ListPersonalRecords,
		connect.WithSchema(analyticsServiceMethods.ByName("ListPersonalRecords")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceRecalculateMetricsHandler := connect.NewUnaryHandler(
		AnalyticsServiceRecalculateMetricsProcedure,
		svc.RecalculateMetrics,
		connect.WithSchema(analyticsServiceMethods.ByName("RecalculateMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetWorkoutCalendarHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetWorkoutCalendarProcedure,
		svc.GetWorkoutCalendar,
		connect.WithSchema(analyticsServiceMethods.ByName("GetWorkoutCalendar")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetMuscleGroupStatsHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetMuscleGroupStatsProcedure,
		svc.GetMuscleGroupStats,
		connect.WithSchema(analyticsServiceMethods.ByName("GetMuscleGroupStats")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetTopExercisesHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetTopExercisesProcedure,
		svc.GetTopExercises,
		connect.WithSchema(analyticsServiceMethods.ByName("GetTopExercises")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetExerciseStatsHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetExerciseStatsProcedure,
		svc.GetExerciseStats,
		connect.WithSchema(analyticsServiceMethods.ByName("GetExerciseStats")),
		connect.WithHandlerOptions(opts...),
	)
	return "/zenx.analytics.v1.AnalyticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnalyticsServiceGetProgressSnapshotProcedure:
			analyticsServiceGetProgressSnapshotHandler.ServeHTTP(w, r)
		case AnalyticsServiceListPersonalRecordsProcedure:
			analyticsServiceListPersonalRecordsHandler.ServeHTTP(w, r)
		case AnalyticsServiceRecalculateMetricsProcedure:
			analyticsServiceRecalculateMetricsHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetWorkoutCalendarProcedure:
			analyticsServiceGetWorkoutCalendarHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetMuscleGroupStatsProcedure:
			analyticsServiceGetMuscleGroupStatsHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetTopExercisesProcedure:
			analyticsServiceGetTopExercisesHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetExerciseStatsProcedure:
			analyticsServiceGetExerciseStatsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnalyticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAnalyticsServiceHandler struct{}

func (UnimplementedAnalyticsServiceHandler) GetProgressSnapshot(context.Context, *connect.Request[v1.GetProgressSnapshotRequest]) (*connect.Response[v1.ProgressSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.analytics.v1.AnalyticsService.GetProgressSnapshot is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) ListPersonalRecords(context.Context, *connect.Request[v1.ListPersonalRecordsRequest]) (*connect.Response[v1.ListPersonalRecordsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.analytics.v1.AnalyticsService.ListPersonalRecords is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) RecalculateMetrics(context.Context, *connect.Request[v1.RecalculateMetricsRequest]) (*connect.Response[v1.RecalculateMetricsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.analytics.v1.AnalyticsService.RecalculateMetrics is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetWorkoutCalendar(context.Context, *connect.Request[v1.GetWorkoutCalendarRequest]) (*connect.Response[v1.GetWorkoutCalendarResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.analytics.v1.AnalyticsService.GetWorkoutCalendar is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetMuscleGroupStats(context.Context, *connect.Request[v1.GetMuscleGroupStatsRequest]) (*connect.Response[v1.GetMuscleGroupStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.analytics.v1.AnalyticsService.GetMuscleGroupStats is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetTopExercises(context.Context, *connect.Request[v1.GetTopExercisesRequest]) (*connect.Response[v1.GetTopExercisesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.analytics.v1.AnalyticsService.GetTopExercises is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetExerciseStats(context.Context, *connect.Request[v1.GetExerciseStatsRequest]) (*connect.Response[v1.GetExerciseStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zenx.analytics.v1.AnalyticsService.GetExerciseStats is not implemented"))
}
